# Master's Degrees from all over!
## Homework_3 for Algorithmic Methods of Data Mining and Laboratory 2023/2024


**Students**:

Baldo Eduardo - eduardobaldo10@gmail.com

Di Giammarco Susanna - digiammarco.1838403@studenti.uniroma1.it

Hadad Ortal - Ortal2824@gmail.com

Zabihi AmirAli - zabihi.Amirali@yahoo.com






In [1]:
#IMPORT LIBRARIES
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
import time
import random
import re
from bs4 import BeautifulSoup
import requests
import lxml
from lxml import html
import os
import pandas as pd


## 1.Data Collection
### 1.1. Get the list of master's degree courses

In [ ]:
#1.1- Reach main URL
base_url = 'https://www.findamasters.com/masters-degrees/msc-degrees/?PG=1'
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get(base_url)
driver.maximize_window()

#WAIT FOR PUBLICITY
try:
    WebDriverWait(driver,20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='signupModal']/div/div/div/i"))).click()
except:
    print("No pop up")
time.sleep(10)

#MASTER COURSES URL
masters_url = []
base_url = 'https://www.findamasters.com/'
base_url_page = 'https://www.findamasters.com/masters-degrees/msc-degrees/?PG='
for n in range(1,401):

    url = base_url_page + str(n)
    res = requests.get(url)
    time.sleep(random.uniform(5, 10))
    soup = BeautifulSoup(res.text, "lxml")

    masters = soup.find_all('a', {'class': 'courseLink text-dark', 'href':True})
    for master in masters:
        masters_url.append(base_url + master['href'])

In [ ]:
#1.1- Checking we collected all the required URL's (6000)
print(len(masters_url))

In [ ]:
#1.1- Saving the collected URL's in a txt file
with open('urls.txt', 'w') as file:
    # Write each URL to a new line
    for url in masters_url:
        file.write(url + '\n')

### 1.2. Crawl master's degree pages

In [ ]:
#1.2- Saving our txt folder as a list
with open('urls.txt', 'r') as file:
    # Read the file line by line
    urls = [line.strip() for line in file]

In [ ]:
#1.2- Download the HTML of a URL and save it as a file in a folder
def download_and_save(url, i):
    try:
        driver = webdriver.Chrome(ChromeDriverManager().install())
        driver.get(url)
        time.sleep(5)
        html = driver.page_source
        folder_name = f'folder_{i // 15}'
        if not os.path.exists(folder_name):
            os.makedirs(folder_name)
        file_name = f'{i % 15}.html'
        with open(os.path.join(folder_name, file_name), 'w', encoding='utf-8') as f:
            f.write(html)
        driver.quit()
    except Exception as e:
        print(f"An error occurred while downloading {url}: {e}")

Due to the large number of pages we should download, we decided to use Python's concurrent.futures module which use multiple threads. Using this method we are able to execute the 'download_and_save' function over multiple URL's concurrently and to decrease the running time.

In [ ]:
#1.2- Using multiple thread to execute the 'download_and_save' function
import concurrent.futures

with concurrent.futures.ThreadPoolExecutor() as executor:
  # Use the executor to map the function to the URLs
  executor.map(download_and_save, urls, range(len(urls)))

### 1.3 Parse downloaded pages

In [ ]:
column_names = ["courseName",
                "universityName",
                "facultyName",
                "isItFullTime",
                "description",
                "startDate",
                "fees",
                "modality",
                "duration",
                "city",
                "country",
                "administration",
                "url"]

In [ ]:
#1.3- Creating a Data Frame with the required columns
df = pd.DataFrame(columns = column_names)

In [ ]:
#1.3- Collect the data from each HTML file and add it to the Data Frame
for i in range(400):
    folder_name = f'folder_{i}'
    for j in range(15):
        file_name = f'{j}.html'

        with open(os.path.join(folder_name, file_name), 'r', encoding='utf-8') as f:
            contents = f.read()
            soup = BeautifulSoup(contents, 'html.parser')

        try:
            courseName = soup.find("h1", {"class": "course-header__course-title"}).text
        except:
            courseName = ""

        try:
            universityName = soup.find('a', {'class': 'course-header__institution'}).text
        except:
            universityName = ""

        try:
            facultyName = soup.find('a', {'class': 'course-header__department'}).text
        except:
            facultyName = ""

        try:
            FullTime_links= soup.find_all('a', {'class':'concealLink' })
            FullTime = False
            for item in FullTime_links:
                if item['href']== "/masters-degrees/full-time/":
                    FullTime = True
                    break
            isItFullTime= FullTime
        except:
            isItFullTime= False

        try:
            paragraphs = soup.find("div", class_="course-sections course-sections__description col-xs-24")
            paragraphs = paragraphs.find("div", id="Snippet").find_all("p")
            description = " ".join([paragraph.text.strip() for paragraph in paragraphs])
        except:
            description = ""

        try:
            startDate = soup.find("span", {"class": "key-info__start-date"}).text
        except:
            startDate = ""

        try:
            fees = soup.find("div", class_="course-sections course-sections__fees tight col-xs-24")
            fees = fees.find("div", class_="course-sections__content").find("p").text
        except:
            fees = ""

        try:
            modality = soup.find("span", {"class": "key-info__qualification"}).text
        except:
            modality = ""

        try:
            duration = soup.find("span", {"class": "key-info__duration"}).text
        except:
            duration = ""

        try:
            city = soup.find("a", {"class": "card-badge text-wrap text-left badge badge-gray-200 p-2 m-1 font-weight-light course-data course-data__city"}).text
        except:
            city= ""

        try:
            country = soup.find("a", {"class": "card-badge text-wrap text-left badge badge-gray-200 p-2 m-1 font-weight-light course-data course-data__country"}).text
        except:
            country = ""

        online_course = soup.find("a", {"class": "course-data__online"})
        on_campus_course = soup.find("a", {"class": "course-data__on-campus"})
        if online_course is None and on_campus_course is None:
            administration = ""
        elif online_course is None:
            administration = on_campus_course.text
        elif on_campus_course is None:
            administration = online_course.text
        else:
            administration = online_course.text + ', ' + on_campus_course.text

        url = soup.find("link", rel="canonical")["href"]

        data = {"courseName": courseName,
                "universityName": universityName,
                "facultyName": facultyName,
                "isItFullTime": isItFullTime,
                "description": description,
                "startDate": startDate,
                "fees": fees,
                "modality": modality,
                "duration": duration,
                "city": city,
                "country": country,
                "administration": administration,
                "url": url}

        df_t = pd.DataFrame(columns=column_names)
        df_t = pd.concat([df_t, pd.DataFrame([data], columns=df_t.columns)], ignore_index=True)
        df_t.to_csv(f"courses/course_{(i*15) +j}.tsv", sep="\t", index=False)
        df = df.append(data, ignore_index=True)

In [ ]:
#1.3- Checking we added all the data (6000)
print(df.shape[0])

6000


## 2.Search Engine

### 2.0 Preprocessing

#### 2.0.0) Preprocessing the text

Firstly, we need to read the contents of the csv file that we obtained in Q1.

In [165]:
dataset = pd.read_csv("./merged_courses.tsv", delimiter="\t")

We can take a look at what it looks like:

In [166]:
dataset.head()

courseName  \
0        3D Design for Virtual Environments - MSc   
1                    Accounting and Finance - MSc   
2                       Analytical Toxicology MSc   
3             Entrepreneurship & Innovation - MSc   
4    Amputation and Prosthetic Rehabilitation MSc   

                  universityName                                  facultyName  \
0  Glasgow Caledonian University  School of Engineering and Built Environment   
1            University of Leeds             Leeds University Business School   
2          King’s College London          Faculty of Life Sciences & Medicine   
3         Trinity College Dublin                      Trinity Business School   
4      University of Southampton   Faculty of Environmental and Life Sciences   

   isItFullTime                                        description  \
0          True  3D visualisation and animation play a role in ...   
1          True  Businesses and governments rely on sound finan...   
2          True  The Analytical Toxicology MSc is a unique stud...   
3          True  This programme is designed to equip students w...   
4          True  Enhance your practice at a global top 100* uni...   

    startDate                                               fees modality  \
0   September  Please see the university website for further ...      MSc   
1   September  UK: £18,000 (Total) International: £34,750 (To...      MSc   
2  See Course  Please see the university website for further ...      MSc   
3   September  Please see the university website for further ...      MSc   
4   September  Please see the university website for further ...      MSc   

                                 duration         city         country  \
0                        1 year full-time      Glasgow  United Kingdom   
1                        1 year full time        Leeds  United Kingdom   
2                     Full-time: One year       London  United Kingdom   
3                        1 year full-time       Dublin         Ireland   
4  1 Year Full Time / 2-4 Years Part Time  Southampton  United Kingdom   

  administration                                                url  
0      On Campus  https://www.findamasters.com/masters-degrees/c...  
1      On Campus  https://www.findamasters.com/masters-degrees/c...  
2      On Campus  https://www.findamasters.com/masters-degrees/c...  
3      On Campus  https://www.findamasters.com/masters-degrees/c...  
4      On Campus  https://www.findamasters.com/masters-degrees/c...

#### Stemming with NLTK

We can use the NLTK library for stemming purposes:

In [167]:
from nltk.stem import *

Firstly, we remove all the rows that contain a NULL description:

In [168]:
dataset = dataset[dataset.description != '']

In [169]:
dataset = dataset.dropna(subset=['description'])

As you may have noticed, the description cells include a lot of "\n" characters in them. So, in order to remove them, we use this, and take another look at the cleaner dataset:

In [170]:
# Replace '\n' with a space or empty string as you prefer
dataset['description'] = dataset['description'].str.replace('\n', ' ', regex=False)
dataset.description.head()

0    3D visualisation and animation play a role in ...
1    Businesses and governments rely on sound finan...
2    The Analytical Toxicology MSc is a unique stud...
3    This programme is designed to equip students w...
4    Enhance your practice at a global top 100* uni...
Name: description, dtype: object

##### Port Stemmer

One of the most common methods for stemming is Porter Stemmer:

In [171]:
porterstemmer = PorterStemmer()

We create a new column to house the stemmed version of the description column, called "descr_stem":

In [172]:
dataset['descr_stem'] = dataset.description.apply(lambda row: [porterstemmer.stem(word) for word in row.split(' ')])

We can see how the list created by splitting and stemming the description column of the 1st row looks like:

In [173]:
lst_porter = [porterstemmer.stem(word) for word in dataset.loc[0,'description'].split(' ')]
lst_porter

['3d',
 'visualis',
 'and',
 'anim',
 'play',
 'a',
 'role',
 'in',
 'mani',
 'areas,',
 'and',
 'the',
 'popular',
 'of',
 'these',
 'media',
 'just',
 'keep',
 'growing.',
 'digit',
 'anim',
 'provid',
 'the',
 'eye-catch',
 'special',
 'effect',
 'in',
 'the',
 '21st',
 "century'",
 'favourit',
 'film',
 'and',
 'televis',
 'shows;',
 '3d',
 'design',
 'is',
 'also',
 'essenti',
 'to',
 'everyday',
 'work',
 'in',
 'everyth',
 'from',
 'comput',
 'game',
 'development,',
 'onlin',
 'virtual',
 'world',
 'develop',
 'and',
 'industri',
 'design',
 'to',
 'marketing,',
 'product',
 'design',
 'and',
 'architecture.',
 "gcu'",
 'programm',
 'in',
 '3d',
 'design',
 'for',
 'virtual',
 'environ',
 'will',
 'help',
 'you',
 'develop',
 'the',
 'skill',
 'to',
 'thrive',
 'in',
 'a',
 'success',
 'career',
 'as',
 'a',
 'visual',
 'designer.',
 'the',
 'programm',
 'is',
 'practic',
 'and',
 'career-focused,',
 'orient',
 'toward',
 'current',
 'industri',
 'needs,',
 'technolog',
 'and',

##### SnowBall Stemmer

Another common method for stemming, is using the SnowBall stemmer:

In [174]:
snowstem = snowball.SnowballStemmer('english')

And then we can take a look at how different the results are between stemming with Porter Stemmer & SnowBall stemmer...
Apparantly, there's not much difference (at least in row #0)

In [175]:
lst_snow = [snowstem.stem(word) for word in dataset.loc[0,'description'].split(' ')]
lst_snow

['3d',
 'visualis',
 'and',
 'anim',
 'play',
 'a',
 'role',
 'in',
 'mani',
 'areas,',
 'and',
 'the',
 'popular',
 'of',
 'these',
 'media',
 'just',
 'keep',
 'growing.',
 'digit',
 'anim',
 'provid',
 'the',
 'eye-catch',
 'special',
 'effect',
 'in',
 'the',
 '21st',
 'centuri',
 'favourit',
 'film',
 'and',
 'televis',
 'shows;',
 '3d',
 'design',
 'is',
 'also',
 'essenti',
 'to',
 'everyday',
 'work',
 'in',
 'everyth',
 'from',
 'comput',
 'game',
 'development,',
 'onlin',
 'virtual',
 'world',
 'develop',
 'and',
 'industri',
 'design',
 'to',
 'marketing,',
 'product',
 'design',
 'and',
 'architecture.',
 'gcu',
 'programm',
 'in',
 '3d',
 'design',
 'for',
 'virtual',
 'environ',
 'will',
 'help',
 'you',
 'develop',
 'the',
 'skill',
 'to',
 'thrive',
 'in',
 'a',
 'success',
 'career',
 'as',
 'a',
 'visual',
 'designer.',
 'the',
 'programm',
 'is',
 'practic',
 'and',
 'career-focused,',
 'orient',
 'toward',
 'current',
 'industri',
 'needs,',
 'technolog',
 'and',
 

#### Removing StopWords with NLTK

In order to create a search engine, we need to get rid of some words that don't give much informatrion and are quite redundant (stop words).

In [176]:
import nltk
from nltk.corpus import stopwords

In [177]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [178]:
lst_stopwords = stopwords.words('english')

Here, we can take a look at all the stopwords included in the NLTK library:

In [179]:
lst_stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

As you can see, words such as "I", "him", "wouldn't" and etc are not relevant, and are going to interfere with our search results.

Now, we can add another column to the dataset -- "descr_clean" -- that only contains the stemmed words that are NOT in the stopwords list:

In [180]:
dataset['descr_clean'] = dataset.description.apply(lambda row: [porterstemmer.stem(word) for word in row.split(' ') if not word in lst_stopwords])

Here's a quick look at the difference between the 2 columns we added at the end...

One -- "descr_stem" -- contains the stemmed version of all of the words.

But "descr_clean" has stopwords removed:

In [181]:
dataset.loc[0, ['descr_clean', 'descr_stem']]

descr_clean    [3d, visualis, anim, play, role, mani, areas,,...
descr_stem     [3d, visualis, and, anim, play, a, role, in, m...
Name: 0, dtype: object

For example, the words "and" and "a" are removed.

#### Removing Punctuation with NLTK

Another step for preparing the description for the search engine, is to remove the punctuation.

In [182]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [183]:
import string

As you can see, we don't need to include these charcters -- '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~' -- in the searching process.

In [184]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

So, again we take a look at the description of the 1st row:

In [185]:
dataset.loc[0, 'description']

"3D visualisation and animation play a role in many areas, and the popularity of these media just keeps growing. Digital animation provides the eye-catching special effects in the 21st century's favourite films and television shows; 3D design is also essential to everyday work in everything from computer games development, online virtual world development and industrial design to marketing, product design and architecture. GCU's programme in 3D Design for Virtual Environments will help you develop the skills to thrive in a successful career as a visual designer. The programme is practical and career-focused, oriented towards current industry needs, technology and practice. No prior knowledge of 3D design is required."

The NLTK's word_tokenizer is another powerful tool to split the words into a string from eachother and return the results as a list.

Instead of using the split() method and NLTK's punctuation package, we can use the word_tokenizer to split the words, and then remove the punctuation using the isalnum() method which checks whether a word contains AlphaNumeric characters or not...

Here's the result of using it on the 1st row's description column:

In [186]:
words = nltk.word_tokenize(dataset.loc[0, 'description'])
words

['3D',
 'visualisation',
 'and',
 'animation',
 'play',
 'a',
 'role',
 'in',
 'many',
 'areas',
 ',',
 'and',
 'the',
 'popularity',
 'of',
 'these',
 'media',
 'just',
 'keeps',
 'growing',
 '.',
 'Digital',
 'animation',
 'provides',
 'the',
 'eye-catching',
 'special',
 'effects',
 'in',
 'the',
 '21st',
 'century',
 "'s",
 'favourite',
 'films',
 'and',
 'television',
 'shows',
 ';',
 '3D',
 'design',
 'is',
 'also',
 'essential',
 'to',
 'everyday',
 'work',
 'in',
 'everything',
 'from',
 'computer',
 'games',
 'development',
 ',',
 'online',
 'virtual',
 'world',
 'development',
 'and',
 'industrial',
 'design',
 'to',
 'marketing',
 ',',
 'product',
 'design',
 'and',
 'architecture',
 '.',
 'GCU',
 "'s",
 'programme',
 'in',
 '3D',
 'Design',
 'for',
 'Virtual',
 'Environments',
 'will',
 'help',
 'you',
 'develop',
 'the',
 'skills',
 'to',
 'thrive',
 'in',
 'a',
 'successful',
 'career',
 'as',
 'a',
 'visual',
 'designer',
 '.',
 'The',
 'programme',
 'is',
 'practical',


We can check whether each word in the obtained list is or isn't an AlphaNumeric word...

In [187]:
for word_i in words:
    print(f"WORD: {word_i}\tisAlNum: {word_i.isalnum()}")


WORD: 3D	isAlNum: True
WORD: visualisation	isAlNum: True
WORD: and	isAlNum: True
WORD: animation	isAlNum: True
WORD: play	isAlNum: True
WORD: a	isAlNum: True
WORD: role	isAlNum: True
WORD: in	isAlNum: True
WORD: many	isAlNum: True
WORD: areas	isAlNum: True
WORD: ,	isAlNum: False
WORD: and	isAlNum: True
WORD: the	isAlNum: True
WORD: popularity	isAlNum: True
WORD: of	isAlNum: True
WORD: these	isAlNum: True
WORD: media	isAlNum: True
WORD: just	isAlNum: True
WORD: keeps	isAlNum: True
WORD: growing	isAlNum: True
WORD: .	isAlNum: False
WORD: Digital	isAlNum: True
WORD: animation	isAlNum: True
WORD: provides	isAlNum: True
WORD: the	isAlNum: True
WORD: eye-catching	isAlNum: False
WORD: special	isAlNum: True
WORD: effects	isAlNum: True
WORD: in	isAlNum: True
WORD: the	isAlNum: True
WORD: 21st	isAlNum: True
WORD: century	isAlNum: True
WORD: 's	isAlNum: False
WORD: favourite	isAlNum: True
WORD: films	isAlNum: True
WORD: and	isAlNum: True
WORD: television	isAlNum: True
WORD: shows	isAlNum: True
WO

Here's a list of all AlphaNumeric words in the above list. We can see that the punctuation has been removed:

In [188]:
[word_i for word_i in words if word_i.isalnum()]

['3D',
 'visualisation',
 'and',
 'animation',
 'play',
 'a',
 'role',
 'in',
 'many',
 'areas',
 'and',
 'the',
 'popularity',
 'of',
 'these',
 'media',
 'just',
 'keeps',
 'growing',
 'Digital',
 'animation',
 'provides',
 'the',
 'special',
 'effects',
 'in',
 'the',
 '21st',
 'century',
 'favourite',
 'films',
 'and',
 'television',
 'shows',
 '3D',
 'design',
 'is',
 'also',
 'essential',
 'to',
 'everyday',
 'work',
 'in',
 'everything',
 'from',
 'computer',
 'games',
 'development',
 'online',
 'virtual',
 'world',
 'development',
 'and',
 'industrial',
 'design',
 'to',
 'marketing',
 'product',
 'design',
 'and',
 'architecture',
 'GCU',
 'programme',
 'in',
 '3D',
 'Design',
 'for',
 'Virtual',
 'Environments',
 'will',
 'help',
 'you',
 'develop',
 'the',
 'skills',
 'to',
 'thrive',
 'in',
 'a',
 'successful',
 'career',
 'as',
 'a',
 'visual',
 'designer',
 'The',
 'programme',
 'is',
 'practical',
 'and',
 'oriented',
 'towards',
 'current',
 'industry',
 'needs',
 'tec

So, this time we revise the "descr_clean" column: We only want the words that have been stemmed and are not stopwords.

In [189]:
dataset['descr_clean'] = dataset.description.apply(lambda row: [porterstemmer.stem(word) for word in nltk.word_tokenize(row) if not word in lst_stopwords and word.isalnum()])
dataset['descr_clean'].head

<bound method NDFrame.head of 0       [3d, visualis, anim, play, role, mani, area, p...
1       [busi, govern, reli, sound, financi, knowledg,...
2       [the, analyt, toxicolog, msc, uniqu, studi, co...
3       [thi, programm, design, equip, student, specia...
4       [enhanc, practic, global, top, 100, univers, g...
                              ...                        
5995    [allergi, increas, global, health, problem, th...
5996    [thi, new, postgradu, certif, allergi, clinic,...
5997    [we, world, allergi, organis, centr, excel, de...
5998    [a, research, degre, open, door, work, researc...
5999    [thi, programm, allow, explor, american, histo...
Name: descr_clean, Length: 5982, dtype: object>

In [190]:
dataset.loc[0, 'descr_clean']

['3d',
 'visualis',
 'anim',
 'play',
 'role',
 'mani',
 'area',
 'popular',
 'media',
 'keep',
 'grow',
 'digit',
 'anim',
 'provid',
 'special',
 'effect',
 '21st',
 'centuri',
 'favourit',
 'film',
 'televis',
 'show',
 '3d',
 'design',
 'also',
 'essenti',
 'everyday',
 'work',
 'everyth',
 'comput',
 'game',
 'develop',
 'onlin',
 'virtual',
 'world',
 'develop',
 'industri',
 'design',
 'market',
 'product',
 'design',
 'architectur',
 'gcu',
 'programm',
 '3d',
 'design',
 'virtual',
 'environ',
 'help',
 'develop',
 'skill',
 'thrive',
 'success',
 'career',
 'visual',
 'design',
 'the',
 'programm',
 'practic',
 'orient',
 'toward',
 'current',
 'industri',
 'need',
 'technolog',
 'practic',
 'no',
 'prior',
 'knowledg',
 '3d',
 'design',
 'requir']

#### SpaCy

One powerful and more modern package that is commonly used is SpaCy. We won't use SpaCy a lot, but we only want to showcase its abilities.

In [191]:
import spacy

In [192]:
import spacy.cli
spacy.cli.download("en_core_web_sm")


✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [193]:
nlp = spacy.load("en_core_web_sm")

In [194]:
doc = nlp(dataset.loc[0, 'description'])

In [195]:
doc

3D visualisation and animation play a role in many areas, and the popularity of these media just keeps growing. Digital animation provides the eye-catching special effects in the 21st century's favourite films and television shows; 3D design is also essential to everyday work in everything from computer games development, online virtual world development and industrial design to marketing, product design and architecture. GCU's programme in 3D Design for Virtual Environments will help you develop the skills to thrive in a successful career as a visual designer. The programme is practical and career-focused, oriented towards current industry needs, technology and practice. No prior knowledge of 3D design is required.

We can iterate through each and every entity of our "doc" variable. And we can see each of their characteristics, such as:

.text: The word itself.

.start_char: How many characters before the word begins.

.end_char: How many characters before the word ends.

.label_: A categorized labeling specific to SpaCy itself.

In [196]:
for ent_i in doc.ents:
    print(f"TEXT: {ent_i.text}, START_CHAR: {ent_i.start_char}, END_CHAR: {ent_i.end_char}, LABEL_: {ent_i.label_}")

TEXT: Digital, START_CHAR: 112, END_CHAR: 119, LABEL_: ORG
TEXT: the 21st century's, START_CHAR: 175, END_CHAR: 193, LABEL_: DATE
TEXT: GCU, START_CHAR: 426, END_CHAR: 429, LABEL_: ORG
TEXT: 3D Design for Virtual Environments, START_CHAR: 445, END_CHAR: 479, LABEL_: ORG


And we can also look at some other methods of each token:

In [197]:
for token in doc:
    print(token, token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
            token.shape_, token.is_alpha, token.is_stop)

3D 3D 3d ADJ JJ amod dX False False
visualisation visualisation visualisation NOUN NN nsubj xxxx True False
and and and CCONJ CC cc xxx True True
animation animation animation NOUN NN conj xxxx True False
play play play VERB VBP ROOT xxxx True False
a a a DET DT det x True True
role role role NOUN NN dobj xxxx True False
in in in ADP IN prep xx True True
many many many ADJ JJ amod xxxx True True
areas areas area NOUN NNS pobj xxxx True False
, , , PUNCT , punct , False False
and and and CCONJ CC cc xxx True True
the the the DET DT det xxx True True
popularity popularity popularity NOUN NN nsubj xxxx True False
of of of ADP IN prep xx True True
these these these DET DT det xxxx True True
media media medium NOUN NNS pobj xxxx True False
just just just ADV RB advmod xxxx True True
keeps keeps keep VERB VBZ conj xxxx True False
growing growing grow VERB VBG xcomp xxxx True False
. . . PUNCT . punct . False False
Digital Digital digital ADJ JJ amod Xxxxx True False
animation animation anima

As mentioned earlier, we will not use SpaCy for our search engine.

### 2.0.1 Preprocessing the fees column

Moreover, we want the field fees to collect numeric information. As you will see, you scraped textual information for this attribute in the dataset: sketch whatever method you need (using regex, for example, to find currency symbol) to collect information and, in case of multiple information, retrieve only the highest fees. Finally, once you have collected numerical information, you likely will have different currencies: this can be chaotic, so let chatGPT guide you in the choice and deployment of an API to convert this column to a common currency of your choice (it can be USD, EUR or whatever you want). Ultimately, you will have a float column renamed fees (CHOSEN COMMON CURRENCY).

Now, let's take a look at the first ten rows of the fees column:

In [198]:
for fee_i in (dataset.fees[:10]):
    print(fee_i)

Please see the university website for further information on fees for this course.
UK: £18,000 (Total) International: £34,750 (Total)
Please see the university website for further information on fees for this course.
Please see the university website for further information on fees for this course.
Please see the university website for further information on fees for this course.
Part time - £7,050
Please see the university website for further information on fees for this course.
Please see the university website for further information on fees for this course.
Please see the university website for further information on fees for this course.
Our tuition fee for UK students starting full-time study in 2024/25 is £10,310 for the course.  Please see the university website for further information on fees for this course.


And this is just the fees column of the 1st row:

In [199]:
dataset.fees.iloc[0]

'Please see the university website for further information on fees for this course.'

We can see that sometimes no figure has been mentioned. And at other times, several figures may have been mentioned. So, we should take care of that.

##### Making API requests to exchangeratesapi.io for Conversion Rates

Now, we want to use freecurrencyapi API to gather data about the latest exchange rates:

In [200]:
pip install git+https://github.com/everapihq/freecurrencyapi-python.git

  Cloning https://github.com/everapihq/freecurrencyapi-python.git to c:\users\hp\appdata\local\temp\pip-req-build-rtj6cfed
  Resolved https://github.com/everapihq/freecurrencyapi-python.git to commit c32c4dc9df5de4cf0d4940c0c27efc5fc8473bdf
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Note: you may need to restart the kernel to use updated packages.


  Running command git clone --filter=blob:none --quiet https://github.com/everapihq/freecurrencyapi-python.git 'C:\Users\HP\AppData\Local\Temp\pip-req-build-rtj6cfed'

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


We use our own personal API code to fetch data.

In [201]:
import freecurrencyapi
client = freecurrencyapi.Client('fca_live_gN70PpWZqBXZc2mLgxw9mcWxOAnrO1el551fuHET')

We can also check the status of our connection and account info:

In [202]:
print(client.status())

{'account_id': 247677987040923648, 'quotas': {'month': {'total': 5000, 'used': 38, 'remaining': 4962}, 'grace': {'total': 0, 'used': 0, 'remaining': 0}}}


The line below gives us a dictionary of the latest exchange rates:

In [203]:
rates = client.latest()
print(rates)

{'data': {'AUD': 1.517720281, 'BGN': 1.7879202647, 'BRL': 4.9032607676, 'CAD': 1.3628301552, 'CHF': 0.8818901262, 'CNY': 7.1494211881, 'CZK': 22.2857136553, 'DKK': 6.8067808994, 'EUR': 0.9140101319, 'GBP': 0.7933701413, 'HKD': 7.7907714857, 'HRK': 7.0415007622, 'HUF': 347.8111229695, 'IDR': 15549.09610602, 'ILS': 3.7370105664, 'INR': 83.3264696455, 'ISK': 137.721773248, 'JPY': 149.3962572719, 'KRW': 1301.7837136825, 'MXN': 17.1198218582, 'MYR': 4.6842604793, 'NOK': 10.6997616391, 'NZD': 1.641330317, 'PHP': 55.4352464061, 'PLN': 3.9868206143, 'RON': 4.5406906708, 'RUB': 89.5235117971, 'SEK': 10.4459612245, 'SGD': 1.3378102087, 'THB': 35.306006855, 'TRY': 28.8355730652, 'USD': 1, 'ZAR': 18.79677309}}


##### Extracting & Converting Fees

REGEX is a powerful tool we can use to identify where and how some characters have been used in a string. This helps us identify the fee figures.

So we need to import it at first:

In [204]:
import re

This is a function defined to extract & convert the fees.

In [205]:
def extract_and_convert_fees(row, rates):
    max_fee_usd = 0  # Initialize the maximum fee variable
    # Define the currency symbols which will be used to identify the currency in the regex pattern.
    currency_symbols = {
        'USD': r'\$',
        'EUR': r'€',
        'JPY': r'¥',
        'GBP': r'£',
        'AUD': r'A\$',
        'CAD': r'C\$',
        'CHF': r'Fr',
        'CNY': r'¥',  # The same symbol as JPY, might need additional context to differentiate
        'HKD': r'HK\$',
        'NZD': r'NZ\$'
    }

    # Regex to find numbers - this is a simplistic pattern
    for currency, symbol in currency_symbols.items():
        pattern = rf'{symbol}(\d+(?:,\d{{3}})*(\.\d+)?)'
        matches = re.findall(pattern, row)
        for match in matches:
            # Remove commas and convert to float
            num = float(match[0].replace(',', ''))
            # Multiply by the conversion rate to get the amount in USD
            if currency in rates['data']:
                num *= rates['data'][currency]
                max_fee_usd = max(max_fee_usd, num)

    return max_fee_usd

We can see an example usage, where the function correctly identifies the two amounts (15K€ & 13K£). Converts them both to the USD$ and finds the max amount and returns it:

In [206]:
# Example usage:
row = "The tuition fee is €15,000 or £13,000 based on the current exchange rates."

# Calculate the fee in USD
fee_in_usd = extract_and_convert_fees(row, rates)
print(f"The fee in USD is: {fee_in_usd}")

The fee in USD is: 13710.1519785


In [207]:
print(dataset.head())

                                       courseName  \
0        3D Design for Virtual Environments - MSc   
1                    Accounting and Finance - MSc   
2                       Analytical Toxicology MSc   
3             Entrepreneurship & Innovation - MSc   
4    Amputation and Prosthetic Rehabilitation MSc   

                  universityName                                  facultyName  \
0  Glasgow Caledonian University  School of Engineering and Built Environment   
1            University of Leeds             Leeds University Business School   
2          King’s College London          Faculty of Life Sciences & Medicine   
3         Trinity College Dublin                      Trinity Business School   
4      University of Southampton   Faculty of Environmental and Life Sciences   

   isItFullTime                                        description  \
0          True  3D visualisation and animation play a role in ...   
1          True  Businesses and governments rely on so

Or, as another example, we can look at fee figure converted to USD$ at row 5:

In [208]:
# This will apply the function to the first row's 'fee' value only
fee_in_usd = extract_and_convert_fees(dataset['fees'].iloc[5], rates)
print(f"The fee in USD is: {fee_in_usd}")


The fee in USD is: 5593.259496165


In [209]:
import numpy as np

We should pay attention to the fact that some rows will return NaN values. So, when creating the new "fees_in_usd" coumn, we need to take care of them as well:

In [210]:

# Apply the function to every row, handling floats by converting them to strings
dataset['fees_in_usd'] = dataset['fees'].apply(lambda row: extract_and_convert_fees(str(row), rates) if not pd.isnull(row) else np.nan)


Now, we can see that in places where no fee figure has been mentioned, the amount represented in our new last column is 0.0

In [211]:
dataset.head(10)

courseName  \
0           3D Design for Virtual Environments - MSc   
1                       Accounting and Finance - MSc   
2                          Analytical Toxicology MSc   
3                Entrepreneurship & Innovation - MSc   
4       Amputation and Prosthetic Rehabilitation MSc   
5          Anaesthesia and Perioperative Science MSc   
6    Analogue and Digital Integrated Circuit Desi...   
7                  Analytical Bioscience (MSc/PGDip)   
8                         Analytical Chemistry (MSc)   
9                         Analytical Chemistry (MSc)   

                   universityName  \
0   Glasgow Caledonian University   
1             University of Leeds   
2           King’s College London   
3          Trinity College Dublin   
4       University of Southampton   
5       University College London   
6         Imperial College London   
7  Birkbeck, University of London   
8             Kingston University   
9     Sheffield Hallam University   

                                         facultyName  isItFullTime  \
0        School of Engineering and Built Environment          True   
1                   Leeds University Business School          True   
2                Faculty of Life Sciences & Medicine          True   
3                            Trinity Business School          True   
4         Faculty of Environmental and Life Sciences          True   
5     Division of Surgery and Interventional Science         False   
6              Electrical and Electronic Engineering          True   
7                         School of Natural Sciences          True   
8  Faculty of Health, Science, Social Care and Ed...          True   
9                               Postgraduate Courses          True   

                                         description           startDate  \
0  3D visualisation and animation play a role in ...           September   
1  Businesses and governments rely on sound finan...           September   
2  The Analytical Toxicology MSc is a unique stud...          See Course   
3  This programme is designed to equip students w...           September   
4  Enhance your practice at a global top 100* uni...           September   
5  The MSc Anaesthesia and Perioperative Science ...    March, September   
6  Our MSc in Analogue and Digital Integrated Cir...             October   
7  Our analytical bioscience postgraduate course ...    October, January   
8  You will study good measurement and scientific...  September, January   
9  Apply for the part-time course here. Work in c...           September   

                                                fees            modality  \
0  Please see the university website for further ...                 MSc   
1  UK: £18,000 (Total) International: £34,750 (To...                 MSc   
2  Please see the university website for further ...                 MSc   
3  Please see the university website for further ...                 MSc   
4  Please see the university website for further ...                 MSc   
5                                 Part time - £7,050                 MSc   
6  Please see the university website for further ...                 MSc   
7  Please see the university website for further ...          MSc, PGDip   
8  Please see the university website for further ...                 MSc   
9  Our tuition fee for UK students starting full-...  MSc, PGDip, PGCert   

                                            duration         city  \
0                                   1 year full-time      Glasgow   
1                                   1 year full time        Leeds   
2                                Full-time: One year       London   
3                                   1 year full-time       Dublin   
4             1 Year Full Time / 2-4 Years Part Time  Southampton   
5                                  2 years part time       London   
6                                   1 year full-time       London   
7              1 yea

### 2.1. Conjunctive query

For the first version of the search engine, we narrowed our interest to the description of each course. It means that you will evaluate queries only concerning the course's description.

#### 2.1.1 Create your index!

Before building the index,

Create a file named vocabulary, in the format you prefer, that maps each word to an integer (term_id).
Then, the first brick of your homework is to create the Inverted Index. It will be a dictionary in this format:

{
term_id_1:[document_1, document_2, document_4],
term_id_2:[document_1, document_3, document_5, document_6],
...}
where document_i is the id of a document that contains that specific word.

Hint: Since you do not want to compute the inverted index every time you use the Search Engine, it is worth thinking about storing it in a separate file and loading it in memory when needed.

Let's take a look again at the the "descr_clean" column:

In [212]:
dataset.descr_clean

0       [3d, visualis, anim, play, role, mani, area, p...
1       [busi, govern, reli, sound, financi, knowledg,...
2       [the, analyt, toxicolog, msc, uniqu, studi, co...
3       [thi, programm, design, equip, student, specia...
4       [enhanc, practic, global, top, 100, univers, g...
                              ...                        
5995    [allergi, increas, global, health, problem, th...
5996    [thi, new, postgradu, certif, allergi, clinic,...
5997    [we, world, allergi, organis, centr, excel, de...
5998    [a, research, degre, open, door, work, researc...
5999    [thi, programm, allow, explor, american, histo...
Name: descr_clean, Length: 5982, dtype: object

In order to create the vocabulary, we can use either of these 2 approaches:

##### Approach 1: Using Python Sets

We can define an empty set at first:

In [213]:
vocabulary = set()

And for each word in each row, we can consider adding them to the set:

In [214]:
dataset.descr_clean.apply(lambda row: [vocabulary.add(word) for word in row])

0       [None, None, None, None, None, None, None, Non...
1       [None, None, None, None, None, None, None, Non...
2       [None, None, None, None, None, None, None, Non...
3       [None, None, None, None, None, None, None, Non...
4       [None, None, None, None, None, None, None, Non...
                              ...                        
5995    [None, None, None, None, None, None, None, Non...
5996    [None, None, None, None, None, None, None, Non...
5997    [None, None, None, None, None, None, None, Non...
5998    [None, None, None, None, None, None, None, Non...
5999    [None, None, None, None, None, None, None, Non...
Name: descr_clean, Length: 5982, dtype: object

Obviously, we'll see the words that have been used repeatedly only once in the set:

In [215]:
vocabulary

{'person',
 'scan',
 'american',
 'tidal',
 'saturday',
 'ami',
 'port',
 'unlock',
 'left',
 'sp5',
 'carv',
 'decreas',
 'organiz',
 'diagnos',
 'bangor',
 'let',
 'unbias',
 'familiaris',
 'gdc',
 'addict',
 'radiotherapist',
 'eventu',
 't',
 '100',
 'substanti',
 'economist',
 'brim',
 'subdisciplin',
 'downstream',
 'borrow',
 '6th',
 'measur',
 'solv',
 'malt',
 'sowi',
 'mening',
 'afield',
 'properli',
 'convinc',
 'immunologist',
 'reject',
 'myriad',
 'smartest',
 'futur',
 'curat',
 'psychophysiolog',
 'judgment',
 'wildfir',
 'ukrain',
 'hadoop',
 'norwegian',
 'leagu',
 'navig',
 'smaller',
 'preserv',
 '20191',
 'qualif',
 'unpreced',
 '31st',
 'grass',
 'crippl',
 'price',
 'spark',
 'commod',
 'reinvigor',
 'decolonis',
 'lewi',
 'molecul',
 '20',
 'chemist',
 'manageri',
 'quarri',
 'epilept',
 'importantli',
 'biorefineri',
 'deem',
 'electron',
 'imarest',
 'particular',
 'hunt',
 'biopharmaceut',
 'circuit',
 'protocol',
 '1953',
 'victorian',
 'forese',
 'atoc',
 

##### Approach 2: Using Python Collections

Another approach is by using the counter and reduce packages:

In [216]:
from collections import Counter
from functools import reduce

In [217]:
vocabulary_alt = Counter(reduce(lambda x, y: x + y, dataset.descr_clean.values)).keys()

In [218]:
vocabulary_alt

dict_keys(['3d', 'visualis', 'anim', 'play', 'role', 'mani', 'area', 'popular', 'media', 'keep', 'grow', 'digit', 'provid', 'special', 'effect', '21st', 'centuri', 'favourit', 'film', 'televis', 'show', 'design', 'also', 'essenti', 'everyday', 'work', 'everyth', 'comput', 'game', 'develop', 'onlin', 'virtual', 'world', 'industri', 'market', 'product', 'architectur', 'gcu', 'programm', 'environ', 'help', 'skill', 'thrive', 'success', 'career', 'visual', 'the', 'practic', 'orient', 'toward', 'current', 'need', 'technolog', 'no', 'prior', 'knowledg', 'requir', 'busi', 'govern', 'reli', 'sound', 'financi', 'underpin', 'strategi', 'thi', 'cours', 'profession', 'advanc', 'modern', 'theori', 'account', 'control', 'well', 'understand', 'organis', 'context', 'you', 'cover', 'fundament', 'topic', 'corpor', 'financ', 'report', 'option', 'modul', 'allow', 'specialis', 'rang', 'intern', 'forens', 'abl', 'appli', 'learn', 'case', 'studi', 'simul', 'test', 'genuin', 'scenario', 'analyt', 'toxicolog',

##### Assign Unique ID to each item in the Vocab

In order to make the inverted matrix, we need to assign INT values to each term in the Vocab...

This can be done in 2 ways:

###### Approach 1: Using For-Loop

In [219]:
index = {}
unique_id = 1
for word in list(vocabulary_alt):
  index[unique_id] = word
  unique_id+=1

In [220]:
index

{1: '3d',
 2: 'visualis',
 3: 'anim',
 4: 'play',
 5: 'role',
 6: 'mani',
 7: 'area',
 8: 'popular',
 9: 'media',
 10: 'keep',
 11: 'grow',
 12: 'digit',
 13: 'provid',
 14: 'special',
 15: 'effect',
 16: '21st',
 17: 'centuri',
 18: 'favourit',
 19: 'film',
 20: 'televis',
 21: 'show',
 22: 'design',
 23: 'also',
 24: 'essenti',
 25: 'everyday',
 26: 'work',
 27: 'everyth',
 28: 'comput',
 29: 'game',
 30: 'develop',
 31: 'onlin',
 32: 'virtual',
 33: 'world',
 34: 'industri',
 35: 'market',
 36: 'product',
 37: 'architectur',
 38: 'gcu',
 39: 'programm',
 40: 'environ',
 41: 'help',
 42: 'skill',
 43: 'thrive',
 44: 'success',
 45: 'career',
 46: 'visual',
 47: 'the',
 48: 'practic',
 49: 'orient',
 50: 'toward',
 51: 'current',
 52: 'need',
 53: 'technolog',
 54: 'no',
 55: 'prior',
 56: 'knowledg',
 57: 'requir',
 58: 'busi',
 59: 'govern',
 60: 'reli',
 61: 'sound',
 62: 'financi',
 63: 'underpin',
 64: 'strategi',
 65: 'thi',
 66: 'cours',
 67: 'profession',
 68: 'advanc',
 69: '

###### Approach 2: Using Pandas DataFrames

We create a Pandas DataFrame called "terms". Its first column will be named "term" and it'll simply house the terms of our vocab.

In [221]:
terms = pd.DataFrame(data=list(vocabulary_alt), columns=['term'])

In [222]:
terms

term
0               3d
1         visualis
2             anim
3             play
4             role
...            ...
6902      recherch
6903   mathématiqu
6904        allerg
6905       slaveri
6906  dictatorship

[6907 rows x 1 columns]

##### Creating the Inverted Index

Question: Which documents (from 0 to 5999) contain the word "3D" in them?
PS: terms.loc[0, "term"] is "3D"

In [223]:
dataset.descr_clean.apply(lambda row: terms.loc[0, "term"] in row)

0        True
1       False
2       False
3       False
4       False
        ...  
5995    False
5996    False
5997    False
5998    False
5999    False
Name: descr_clean, Length: 5982, dtype: bool

Using a mask to see exactly which documents contain the word "3D"

In [224]:
dataset.index[dataset.descr_clean.apply(lambda row: terms.loc[0, "term"] in row)]

Index([   0,  923, 1592, 2033, 2036, 2037, 3239, 3339, 3691, 4401, 4467, 5309,
       5346, 5357, 5868],
      dtype='int64')

Again, we use the same mask, but this time, in order to see courseName and description

In [225]:
dataset[["courseName", "description"]][dataset.descr_clean.apply(lambda row: terms.loc[0, "term"] in row)]

courseName  \
0              3D Design for Virtual Environments - MSc   
923                    Chemistry - MPhil/MSc (Research)   
1592                        Creative Technologies (MSc)   
2033                           Digital Anthropology MSc   
2036                    Digital Audio Engineering - MSc   
2037                    Digital Audio Engineering - MSc   
3239                             Game Engineering - MSc   
3339    Geospatial Sciences (Building Information Mo...   
3691                                      Physics - MSc   
4401                     3D Computer Games Design - MSc   
4467    Landscape Archaeology and Digital Heritage -...   
5309               Master of Science in Computer Vision   
5346                       Additive Manufacturing - MSc   
5357         Additive Manufacturing and 3D Printing MSc   
5868    Advanced Product Design Engineering & Manufa...   

                                            description  
0     3D visualisation and animation play a role in ...  
923   Our research groups are involved in projects a...  
1592  Combine your passion for creative art and desi...  
2033  The MSc in Digital Anthropology, the first and...  
2036  On our MSc in Digital Audio Engineering, you w...  
2037  On our MSc in Digital Audio Engineering, you w...  
3239  UCA's new MSc Game Engineering course aims to ...  
3339  The Geospatial Sciences (Building Information ...  
3691  This course is for you if you’re interested in...  
4401  Get a flying start in the games industry. If y...  
4467  3D methods of digitally documenting objects, s...  
5309  Introduction This scientific field studies how...  
5346  Additive Manufacturing, or 3D printing, is an ...  
5357  Whether it is creating advanced engineering co...  
5868  This course examines the latest developments i...

The only reason that we use the "tqdm.notebook" is to use the "progress_apply" method later:

In [226]:
from tqdm.notebook import tqdm

tqdm.pandas()

So now, we want to add another column to the "terms" dataframe -- called "reverse". It contains a list of all the rows that include that specific term/word.

In [227]:

terms['reverse'] = terms.term.progress_apply(lambda item: list(dataset.loc[dataset.descr_clean.apply(lambda row: item in row)].index))

  0%|          | 0/6907 [00:00<?, ?it/s]

Let's take a look at the top 10:

In [228]:
terms.loc[0:9]

term                                            reverse
0        3d  [0, 923, 1592, 2033, 2036, 2037, 3239, 3339, 3...
1  visualis  [0, 78, 306, 470, 471, 474, 738, 754, 796, 797...
2      anim  [0, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34...
3      play  [0, 34, 42, 43, 66, 103, 249, 250, 254, 357, 3...
4      role  [0, 5, 31, 33, 34, 43, 46, 58, 103, 107, 119, ...
5      mani  [0, 33, 36, 49, 79, 94, 95, 99, 102, 109, 111,...
6      area  [0, 4, 11, 13, 18, 36, 47, 51, 53, 71, 75, 90,...
7   popular  [0, 62, 322, 532, 1047, 1164, 1165, 1166, 1519...
8     media  [0, 54, 196, 284, 363, 364, 447, 476, 546, 741...
9      keep  [0, 119, 396, 462, 530, 619, 686, 687, 1332, 1...

For easier use, let's save our inverted index into a csv file:

In [229]:
terms.to_csv('inverted_index.csv', index=False)

#### Executing the Query

Finally, we can define a very simple search engine function -- "execute_query":

In [230]:
def execute_query(query, inverted_index, dataset):
    # Split the query into terms and stem each term
    query_terms = [porterstemmer.stem(word) for word in query.lower().split()]

    # Retrieve the list of document indices for each query term
    list_of_documents = [set(inverted_index[inverted_index['term'] == term_i]['reverse'].values[0])
                         for term_i in query_terms if term_i in inverted_index['term'].values]

    # Intersect the document lists to find documents that contain all query terms
    if list_of_documents:
        docs_containing_all_terms = set.intersection(*list_of_documents)
        # Convert set to list before using it as an indexer
        docs_containing_all_terms = list(docs_containing_all_terms)
    else:
        docs_containing_all_terms = []

    results = dataset.loc[docs_containing_all_terms, ['courseName', 'universityName', 'description', 'url']]

    return results.reset_index(drop=True)


Example usage of the search engine:

In [231]:
# Example usage:
sample_query = "advanced knowledge"
query_results = execute_query(sample_query, terms, dataset)
(query_results)

courseName                 universityName  \
0            Accounting and Finance - MSc            University of Leeds   
1               Analytical Toxicology MSc          King’s College London   
2         Digital Design and Branding MSc       Brunel University London   
3      Digital Design and Manufacture MSc        University of Edinburgh   
4                     Stroke Medicine MSc           Learna | Diploma MSc   
..                                    ...                            ...   
444          International Business - MSc          University of Glasgow   
445               Diabetes Practice - MSc             Cardiff University   
446    Diabetes Practice MSc/PGDip/PGCert             Swansea University   
447              Diagnostic Imaging - MSc  Glasgow Caledonian University   
448            Diagnostic Radiography MSc        University College Cork   

                                           description  \
0    Businesses and governments rely on sound finan...   
1    The Analytical Toxicology MSc is a unique stud...   
2    Our Digital Design and Branding MSc degree is ...   
3    With the transition to industry 4.0, digital d...   
4    Postgraduate training in stroke care is limite...   
..                                                 ...   
444  International Business will provide you with a...   
445  The MSc Diabetes Practice aims to equip health...   
446  If you are a health professional with a specia...   
447  Designed to train a new generation of leaders ...   
448  Our MSc Diagnostic Radiography programme is an...   

                                                   url  
0    https://www.findamasters.com/masters-degrees/c...  
1    https://www.findamasters.com/masters-degrees/c...  
2    https://www.findamasters.com/masters-degrees/c...  
3    https://www.findamasters.com/masters-degrees/c...  
4    https://www.findamasters.com/masters-degrees/c...  
..                                                 ...  
444  https://www.findamasters.com/masters-degrees/c...  
445  https://www.findamasters.com/masters-degrees/c...  
446  https://www.findamasters.com/masters-degrees/c...  
447  https://www.findamasters.com/masters-degrees/c...  
448  https://www.findamasters.com/masters-degrees/c...  

[449 rows x 4 columns]

Another example usage (more specific):

In [232]:
# Example usage:
sample_query = "financial management"
query_results = execute_query(sample_query, terms, dataset)
(query_results)

courseName  \
0           Master in Global Management at ESMT Berlin   
1                         Accounting and Finance - MSc   
2                MSc Finance and Investment Management   
3                     Master in Health Care Management   
4                             FinTech Management - MSc   
..                                                 ...   
231                       Engineering Management (MSc)   
232    Master in Global Logistics and Supply Chain ...   
233                                  Master of Finance   
234                Construction Project Management MSc   
235            MSc Project Management for Construction   

                        universityName  \
0                          ESMT Berlin   
1                    Bangor University   
2              University of Liverpool   
3                   Harvard University   
4                    Ulster University   
..                                 ...   
231      University of Gloucestershire   
232  Kuehne Logistics University - KLU   
233           York University (Canada)   
234           University of Portsmouth   
235           University of Portsmouth   

                                           description  \
0    The ESMT Berlin Master in Global Management pr...   
1    This degree programme provides the opportunity...   
2    A career in finance and investment management ...   
3    Today, leading a health care organization take...   
4    Gain a solid grounding in key aspects of finan...   
..                                                 ...   
231  The modules you will study include Leading Eng...   
232  Our MSc in Global Logistics and Supply Chain M...   
233  The “must-have” degree for specialized financi...   
234  Establish yourself in the global construction ...   
235  Start date: January 2024 A level of management...   

                                                   url  
0    https://www.findamasters.com/masters-degrees/c...  
1    https://www.findamasters.com/masters-degrees/c...  
2    https://www.findamasters.com/masters-degrees/c...  
3    https://www.findamasters.com/masters-degrees/c...  
4    https://www.findamasters.com/masters-degrees/c...  
..                                                 ...  
231  https://www.findamasters.com/masters-degrees/c...  
232  https://www.findamasters.com/masters-degrees/c...  
233  https://www.findamasters.com/masters-degrees/c...  
234  https://www.findamasters.com/masters-degrees/c...  
235  https://www.findamasters.com/masters-degrees/c...  

[236 rows x 4 columns]

We can see it works pretty well.

### 2.2 Conjunctive query & Ranking score

#### TF-IDF

Now, another way to define our search engine is to use the TF-IDF score:

In [233]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [234]:
tfidf = TfidfVectorizer(input='content', lowercase=False, tokenizer=lambda text: text) # , max_df=0.1

In [235]:
results = tfidf.fit_transform(dataset.descr_clean)

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [236]:
results

<5982x6907 sparse matrix of type '<class 'numpy.float64'>'
	with 232331 stored elements in Compressed Sparse Row format>

In [237]:
result_dense = results.todense()

In [238]:

result_dense

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

Finally, we can make a Pandas DataFrame using the score in the "descr_clean" column:

In [239]:
tfidf_data = pd.DataFrame(result_dense.tolist(), index=dataset.index, columns=tfidf.get_feature_names_out())

In [240]:
len(tfidf_data)

5982

In [241]:
tfidf_data

1   10       100  1000  104k   11  11th   12  120  125k  ...  zoonosi  \
0     0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
1     0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
2     0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
3     0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
4     0.0  0.0  0.141114   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
...   ...  ...       ...   ...   ...  ...   ...  ...  ...   ...  ...      ...   
5995  0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
5996  0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
5997  0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
5998  0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
5999  0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   

      zoonot   zu  zudem  zum  zur  zurich  zwingen  école  ísafjörður  
0        0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
1        0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
2        0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
3        0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
4        0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
...      ...  ...    ...  ...  ...     ...      ...    ...         ...  
5995     0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
5996     0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
5997     0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
5998     0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
5999     0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  

[5982 rows x 6907 columns]

Just to get a sense of what the dataframe looks like, we can take a look at some of its middle columns

In [242]:
tfidf_data.iloc[:, 1150:1165]

ced  cedex  cee  cef  ceid  celci  celebr  cell  cellebrit  cellular  \
0     0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
1     0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
2     0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
3     0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
4     0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
...   ...    ...  ...  ...   ...    ...     ...   ...        ...       ...   
5995  0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
5996  0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
5997  0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
5998  0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
5999  0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   

      celtic  cem  cement  cen  ceng  
0        0.0  0.0     0.0  0.0   0.0  
1        0.0  0.0     0.0  0.0   0.0  
2        0.0  0.0     0.0  0.0   0.0  
3        0.0  0.0     0.0  0.0   0.0  
4        0.0  0.0     0.0  0.0   0.0  
...      ...  ...     ...  ...   ...  
5995     0.0  0.0     0.0  0.0   0.0  
5996     0.0  0.0     0.0  0.0   0.0  
5997     0.0  0.0     0.0  0.0   0.0  
5998     0.0  0.0     0.0  0.0   0.0  
5999     0.0  0.0     0.0  0.0   0.0  

[5982 rows x 15 columns]

In [243]:
tfidf_data.loc[terms.term == "3d"]["3d"]

0    0.558084
Name: 3d, dtype: float64

We know that in index=0, the word "3d" has been used a lot. So, let's take a look at how many times it has been used:

In [244]:
Counter(dataset.loc[0, 'descr_clean'])['3d']

4

We know that in index=1, the word "govern" has been used once. So, let's take a look at that:

In [245]:
Counter(dataset.loc[1, 'descr_clean'])['govern']

1

If we look for the word "finance" in tfidf_data, we can see that it has a 0.0 TFIDF score in most of the documents:

In [246]:
# Obviously we cannot mention "finance" exactly as is, but we have to stemm it first into "financ"
tfidf_data.financ

0       0.000000
1       0.213729
2       0.000000
3       0.145655
4       0.000000
          ...   
5995    0.000000
5996    0.000000
5997    0.000000
5998    0.000000
5999    0.000000
Name: financ, Length: 5982, dtype: float64

So, let's take a look at all the documents in which the word "finance" has been used:

In [247]:
tfidf_data.loc[tfidf_data.financ > 0, ['financ']]

financ
1     0.213729
3     0.145655
91    0.080973
93    0.105921
100   0.112638
...        ...
5845  0.227227
5894  0.117534
5932  0.113638
5960  0.081390
5985  0.127563

[464 rows x 1 columns]

In [248]:
dataset[tfidf_data.financ > 0][["courseName", "description"]]

courseName  \
1                          Accounting and Finance - MSc   
3                   Entrepreneurship & Innovation - MSc   
91      Environmental, Social, Governance (ESG) Mana...   
93                           Applied Data Science - MSc   
100     Applied data science for banking and finance...   
...                                                 ...   
5845                        Economics and Finance - MSc   
5894    Advanced Technology for Financial Computing ...   
5932                        Aerospace Engineering (MSc)   
5960                             Agricultural Economics   
5985          Air Transport Planning and Management MSc   

                                            description  
1     Businesses and governments rely on sound finan...  
3     This programme is designed to equip students w...  
91    More than ever ESG is essential for businesses...  
93    Our Applied Data Science Masters programme is ...  
100   The Master’s degree of Applied Data Science fo...  
...                                                 ...  
5845  This course provides an opportunity to combine...  
5894  This programme will provide you with a critica...  
5932  This course provides a strategic and practical...  
5960  Food crises, commodity price booms and busts, ...  
5985  This course has been developed to meet the nee...  

[464 rows x 2 columns]

We can see that the word "you" has been used in a lot of documents, but with a relativley low TFIDF score:

In [249]:
tfidf_data.loc[tfidf_data["you"] > 0]["you"]

1       0.143833
6       0.050562
8       0.108902
15      0.076762
16      0.075500
          ...   
5989    0.076589
5990    0.067682
5991    0.066887
5997    0.057537
5999    0.041176
Name: you, Length: 1486, dtype: float64

We can also create a "descr_len" column and add it at the end of our dataset. It shows the number of terms/words in each decription cell.

In [250]:
dataset['descr_len'] = dataset.descr_clean.apply(lambda row: len(row))

In [251]:
dataset.loc[[1, 2, 9, 12, 14], 'descr_len']

1     59
2     27
9     15
12     5
14    65
Name: descr_len, dtype: int64

### Cosine Similarity

A powerful measure to use in order to create our second search engine is Cosine Similarity.

In [252]:
from sklearn.metrics.pairwise import cosine_similarity

We create a DataFrame that shows the Cosine Similarity between each and every of our 6000 documents.

In [253]:
cossim_data = pd.DataFrame(cosine_similarity(tfidf_data), index=dataset.index, columns=dataset.index)

In [254]:
cossim_data

0         1         2         3         4         5         6     \
0     1.000000  0.044896  0.017311  0.062301  0.028271  0.034360  0.070342   
1     0.044896  1.000000  0.098026  0.096449  0.021572  0.028806  0.026257   
2     0.017311  0.098026  1.000000  0.020816  0.032284  0.042743  0.034030   
3     0.062301  0.096449  0.020816  1.000000  0.012793  0.016779  0.024242   
4     0.028271  0.021572  0.032284  0.012793  1.000000  0.062196  0.013736   
...        ...       ...       ...       ...       ...       ...       ...   
5995  0.030193  0.039091  0.035855  0.035377  0.070859  0.034376  0.014845   
5996  0.012265  0.021720  0.043225  0.043144  0.064227  0.068529  0.000000   
5997  0.034951  0.043321  0.023743  0.030867  0.130874  0.048449  0.016382   
5998  0.029310  0.060824  0.048526  0.055432  0.130633  0.122444  0.037089   
5999  0.005517  0.051947  0.015655  0.012699  0.017076  0.001610  0.006764   

          7         8         9     ...      5990      5991      5992  \
0     0.026444  0.024312  0.040890  ...  0.094114  0.066081  0.060399   
1     0.044869  0.043968  0.095974  ...  0.093382  0.043980  0.026459   
2     0.123045  0.009016  0.123079  ...  0.042001  0.042523  0.029054   
3     0.018312  0.018093  0.011931  ...  0.081671  0.036518  0.042325   
4     0.009294  0.024846  0.065112  ...  0.011187  0.031585  0.020140   
...        ...       ...       ...  ...       ...       ...       ...   
5995  0.030179  0.018701  0.064314  ...  0.016265  0.036910  0.030794   
5996  0.048048  0.009580  0.012659  ...  0.015783  0.067892  0.022590   
5997  0.034180  0.043561  0.000000  ...  0.025717  0.021576  0.020385   
5998  0.064269  0.043021  0.021296  ...  0.029986  0.054539  0.004431   
5999  0.055193  0.013550  0.004577  ...  0.015477  0.051912  0.003271   

          5993      5994      5995      5996      5997      5998      5999  
0     0.015575  0.000000  0.030193  0.012265  0.034951  0.029310  0.005517  
1     0.022829  0.007139  0.039091  0.021720  0.043321  0.060824  0.051947  
2     0.026443  0.020243  0.035855  0.043225  0.023743  0.048526  0.015655  
3     0.019011  0.005042  0.035377  0.043144  0.030867  0.055432  0.012699  
4     0.004987  0.006360  0.070859  0.064227  0.130874  0.130633  0.017076  
...        ...       ...       ...       ...       ...       ...       ...  
5995  0.004916  0.011777  1.000000  0.319122  0.506296  0.056496  0.007913  
5996  0.005718  0.011568  0.319122  1.000000  0.290336  0.085569  0.010977  
5997  0.014168  0.014551  0.506296  0.290336  1.000000  0.126371  0.002369  
5998  0.020900  0.038562  0.056496  0.085569  0.126371  1.000000  0.058893  
5999  0.006021  0.005185  0.007913  0.010977  0.002369  0.058893  1.000000  

[5982 rows x 5982 columns]

For example we can look at all the instances (rows) in which there's a non-zero TF-IDF score for the word "design":

In [255]:
tfidf_data.loc[tfidf_data.design > 0].index

Index([   0,    3,    6,    7,   15,   16,   17,   19,   24,   25,
       ...
       5982, 5984, 5985, 5986, 5987, 5989, 5990, 5991, 5992, 5995],
      dtype='int64', length=1561)

And then we can look at the cosine similarity btwn those documents/rows and every other document:

In [256]:
cossim_data[tfidf_data.loc[tfidf_data.design > 0.1].index]

0         6         61        76        77        85        103   \
0     1.000000  0.070342  0.072319  0.093596  0.082283  0.131585  0.117771   
1     0.044896  0.026257  0.104755  0.065530  0.058123  0.082901  0.027663   
2     0.017311  0.034030  0.127910  0.049959  0.047881  0.027245  0.044165   
3     0.062301  0.024242  0.095927  0.086487  0.066019  0.039841  0.040293   
4     0.028271  0.013736  0.047589  0.018882  0.066568  0.092878  0.028719   
...        ...       ...       ...       ...       ...       ...       ...   
5995  0.030193  0.014845  0.053102  0.048664  0.041260  0.042642  0.051729   
5996  0.012265  0.000000  0.050280  0.058119  0.030327  0.047612  0.022931   
5997  0.034951  0.016382  0.033971  0.036117  0.047220  0.045777  0.025197   
5998  0.029310  0.037089  0.052779  0.081106  0.056889  0.071818  0.031393   
5999  0.005517  0.006764  0.017594  0.020140  0.017402  0.032128  0.018742   

          135       141       147   ...      5868      5884      5892  \
0     0.048727  0.072268  0.086113  ...  0.336127  0.081632  0.119661   
1     0.051501  0.061308  0.070455  ...  0.099293  0.064515  0.095014   
2     0.016520  0.044838  0.024865  ...  0.056523  0.085371  0.070849   
3     0.025827  0.014341  0.054653  ...  0.030551  0.028302  0.063867   
4     0.014086  0.050311  0.033591  ...  0.020747  0.005921  0.067758   
...        ...       ...       ...  ...       ...       ...       ...   
5995  0.016746  0.032387  0.031992  ...  0.033750  0.055963  0.033484   
5996  0.007829  0.016443  0.047491  ...  0.017635  0.013945  0.004876   
5997  0.008867  0.055943  0.039780  ...  0.014877  0.023145  0.051801   
5998  0.025629  0.016667  0.038880  ...  0.010654  0.024576  0.065209   
5999  0.012579  0.046626  0.059199  ...  0.006829  0.012191  0.024984   

          5905      5921      5944      5978      5984      5986      5992  
0     0.065641  0.064134  0.082214  0.085722  0.104644  0.091681  0.060399  
1     0.035909  0.101345  0.074909  0.135355  0.090061  0.055557  0.026459  
2     0.100817  0.012623  0.047672  0.044693  0.049227  0.031767  0.029054  
3     0.046748  0.110292  0.099437  0.073193  0.035708  0.055180  0.042325  
4     0.108476  0.011990  0.031380  0.036305  0.065920  0.030293  0.020140  
...        ...       ...       ...       ...       ...       ...       ...  
5995  0.047577  0.043714  0.029360  0.041091  0.055425  0.039944  0.030794  
5996  0.035962  0.018799  0.027717  0.030348  0.058108  0.014377  0.022590  
5997  0.202021  0.016268  0.026355  0.043296  0.021297  0.009255  0.020385  
5998  0.226728  0.016046  0.035675  0.032132  0.046088  0.038729  0.004431  
5999  0.011402  0.002327  0.006652  0.009459  0.022791  0.030315  0.003271  

[5982 rows x 389 columns]

In [257]:
dataset.loc[[0, 2, 1577]]

courseName  \
0              3D Design for Virtual Environments - MSc   
2                             Analytical Toxicology MSc   
1577    Counselling and Psychotherapy (Professional ...   

                     universityName  \
0     Glasgow Caledonian University   
2             King’s College London   
1577          University of Salford   

                                      facultyName  isItFullTime  \
0     School of Engineering and Built Environment          True   
2             Faculty of Life Sciences & Medicine          True   
1577                 School of Health and Society         False   

                                            description   startDate  \
0     3D visualisation and animation play a role in ...   September   
2     The Analytical Toxicology MSc is a unique stud...  See Course   
1577  During this course, you will undertake an in-d...   September   

                                                   fees    modality  \
0     Please see the university website for further ...         MSc   
2     Please see the university website for further ...         MSc   
1577  Please see the university website for further ...  PGDip, MSc   

                 duration        city         country administration  \
0        1 year full-time     Glasgow  United Kingdom      On Campus   
2     Full-time: One year      London  United Kingdom      On Campus   
1577  2-3 years Part-time  Manchester  United Kingdom      On Campus   

                                                    url  \
0     https://www.findamasters.com/masters-degrees/c...   
2     https://www.findamasters.com/masters-degrees/c...   
1577  https://www.findamasters.com/masters-degrees/c...   

                                             descr_stem  \
0     [3d, visualis, and, anim, play, a, role, in, m...   
2     [the, analyt, toxicolog, msc, is, a, uniqu, st...   
1577  [dure, thi, course,, you, will, undertak, an, ...   

                                            descr_clean  fees_in_usd  \
0     [3d, visualis, anim, play, role, mani, area, p...          0.0   
2     [the, analyt, toxicolog, msc, uniqu, studi, co...          0.0   
1577  [dure, cours, undertak, studi, approach, couns...          0.0   

      descr_len  
0            72  
2            27  
1577         55

### 2nd Inverted Index

Now, let's create the 2nd inverted index ("terms2") dataframe as per the HW description.

We firstly copy our 1st [simple] index into the 2nd one...

In [258]:
terms2 = terms[['term', 'reverse']].copy()

Then, we add another column -- "tfidf_tuples". So now, we can see each term in the "term" column. A list of all the documents that that word has been mentioned in, in the "reverse" column. And finally a tuple of the cosine similarity of each term in each and every document/row it has been mentioned in, in the "tfidf_tuples" column.

In [259]:
terms2['tfidf_tuples'] = terms2.term.apply(lambda term: [(doc_id, tfidf_data.loc[doc_id, term])
                                                       for doc_id in tfidf_data.index if tfidf_data.loc[doc_id, term] > 0])

In [261]:
terms2

term                                            reverse  \
0               3d  [0, 923, 1592, 2033, 2036, 2037, 3239, 3339, 3...   
1         visualis  [0, 78, 306, 470, 471, 474, 738, 754, 796, 797...   
2             anim  [0, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34...   
3             play  [0, 34, 42, 43, 66, 103, 249, 250, 254, 357, 3...   
4             role  [0, 5, 31, 33, 34, 43, 46, 58, 103, 107, 119, ...   
...            ...                                                ...   
6902      recherch                                             [5994]   
6903   mathématiqu                                             [5994]   
6904        allerg                                             [5995]   
6905       slaveri                                             [5999]   
6906  dictatorship                                             [5999]   

                                           tfidf_tuples  
0     [(0, 0.5580842522585211), (923, 0.152852921404...  
1     [(0, 0.11960044691955087), (78, 0.119041928959...  
2     [(0, 0.2184275132043667), (23, 0.5054735077876...  
3     [(0, 0.09312374852562808), (34, 0.077513509080...  
4     [(0, 0.06817038680643188), (5, 0.1066488449838...  
...                                                 ...  
6902                         [(5994, 0.14173977060375)]  
6903                          [(5994, 0.2834795412075)]  
6904                      [(5995, 0.36854338677274523)]  
6905                       [(5999, 0.1549767656797962)]  
6906                       [(5999, 0.1549767656797962)]  

[6907 rows x 3 columns]

We can see for example [in the above cell's results] that the word "3d" has been mentioned in rows [0, 923, ...].

And by looking at the tfidf column we can see that the similarity btwn the word "3d" and doc#0 is 0.5692851031776165.

Furthurmore, the similarity btwn the word "3d" and doc#923 is 0.158603012853.

Etc.

In [262]:
terms2["reverse"]

0       [0, 923, 1592, 2033, 2036, 2037, 3239, 3339, 3...
1       [0, 78, 306, 470, 471, 474, 738, 754, 796, 797...
2       [0, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34...
3       [0, 34, 42, 43, 66, 103, 249, 250, 254, 357, 3...
4       [0, 5, 31, 33, 34, 43, 46, 58, 103, 107, 119, ...
                              ...                        
6902                                               [5994]
6903                                               [5994]
6904                                               [5995]
6905                                               [5999]
6906                                               [5999]
Name: reverse, Length: 6907, dtype: object

In [263]:
terms2["tfidf_tuples"]

0       [(0, 0.5580842522585211), (923, 0.152852921404...
1       [(0, 0.11960044691955087), (78, 0.119041928959...
2       [(0, 0.2184275132043667), (23, 0.5054735077876...
3       [(0, 0.09312374852562808), (34, 0.077513509080...
4       [(0, 0.06817038680643188), (5, 0.1066488449838...
                              ...                        
6902                           [(5994, 0.14173977060375)]
6903                            [(5994, 0.2834795412075)]
6904                        [(5995, 0.36854338677274523)]
6905                         [(5999, 0.1549767656797962)]
6906                         [(5999, 0.1549767656797962)]
Name: tfidf_tuples, Length: 6907, dtype: object

Again, for easier use, we can save our 2nd inverted index into a csv file...

In [264]:
terms2.to_csv('inverted_index2.csv', index=False)

Now, we are ready to create the function for our 2nd [more advanced search engine]:

In [265]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def execute_query2(query, inverted_index, dataset, tfidf_data):
    # Preprocess the query to match the document processing
    query_terms = [porterstemmer.stem(word) for word in query.lower().split()]

    # Find documents that contain all terms in the query
    relevant_docs = set()
    for term in query_terms:
        if term in inverted_index['term'].values:
            docs_with_term = [doc_id for doc_id, _ in inverted_index.loc[inverted_index['term'] == term, 'tfidf_tuples'].iloc[0]]
            if not relevant_docs:
                relevant_docs = set(docs_with_term)
            else:
                relevant_docs.intersection_update(docs_with_term)

    if not relevant_docs:
        return pd.DataFrame()  # If no documents are found, return an empty DataFrame

    # Calculate cosine similarity for each document
    query_vec = tfidf.transform([' '.join(query_terms)])
    similarities = {}
    for doc_id in relevant_docs:
        doc_vec = tfidf_data.loc[doc_id].values.reshape(1, -1)
        similarities[doc_id] = cosine_similarity(query_vec, doc_vec)[0][0]

    # Sort documents by their similarity score
    sorted_doc_ids = sorted(similarities, key=similarities.get, reverse=True)

    # Prepare the results with the similarity score
    results = dataset.loc[sorted_doc_ids, ['courseName', 'universityName', 'description', 'url']]
    results['similarity'] = [similarities[doc_id] for doc_id in sorted_doc_ids]

    return results.reset_index(drop=True)

1st Example usage:

In [266]:
# Example usage
results = execute_query2("advanced knowledge", terms2, dataset, tfidf_data)
(results)

courseName  \
0      Geo-information Science and Earth Observatio...   
1          Advanced Mechanical Engineering - MSc/PGDip   
2                       Air Transport Management (MSc)   
3      Advanced Nurse Practitioner/Professional Pra...   
4                   Gerontological Nursing - MSc/PgDip   
..                                                 ...   
444                       International Business - MSc   
445                            Diabetes Practice - MSc   
446                 Diabetes Practice MSc/PGDip/PGCert   
447                           Diagnostic Imaging - MSc   
448                         Diagnostic Radiography MSc   

                              universityName  \
0                       University of Twente   
1                     Heriot-Watt University   
2                       Cranfield University   
3    University of the Highlands and Islands   
4                     Trinity College Dublin   
..                                       ...   
444                    University of Glasgow   
445                       Cardiff University   
446                       Swansea University   
447            Glasgow Caledonian University   
448                  University College Cork   

                                           description  \
0    INTERESTED IN A CAREER IN SPATIAL DATA SCIENCE...   
1    This programme aims to develop the knowledge a...   
2    You can help solve the challenge as the aviati...   
3    Developed in partnership with expert clinical ...   
4    The aim of this course is to strengthen and de...   
..                                                 ...   
444  International Business will provide you with a...   
445  The MSc Diabetes Practice aims to equip health...   
446  If you are a health professional with a specia...   
447  Designed to train a new generation of leaders ...   
448  Our MSc Diagnostic Radiography programme is an...   

                                                   url  similarity  
0    https://www.findamasters.com/masters-degrees/c...    0.101751  
1    https://www.findamasters.com/masters-degrees/c...    0.060091  
2    https://www.findamasters.com/masters-degrees/c...    0.050153  
3    https://www.findamasters.com/masters-degrees/c...    0.046138  
4    https://www.findamasters.com/masters-degrees/c...    0.044068  
..                                                 ...         ...  
444  https://www.findamasters.com/masters-degrees/c...    0.000000  
445  https://www.findamasters.com/masters-degrees/c...    0.000000  
446  https://www.findamasters.com/masters-degrees/c...    0.000000  
447  https://www.findamasters.com/masters-degrees/c...    0.000000  
448  https://www.findamasters.com/masters-degrees/c...    0.000000  

[449 rows x 5 columns]

2nd Example usage:

In [267]:
# Example usage
results = execute_query2("financial management", terms2, dataset, tfidf_data)
(results)

courseName  \
0                                  Master’s in Finance   
1              Master Financial Management and Control   
2                              Banking and Finance MSc   
3             Finance, Accounting and Management - MSc   
4                MSc Finance and Investment Management   
..                                                 ...   
231                       Accounting and Finance - MSc   
232                       Engineering Management (MSc)   
233    Master in Global Logistics and Supply Chain ...   
234                                  Master of Finance   
235                Construction Project Management MSc   

                                 universityName  \
0         Nova School of Business and Economics   
1      The Hague University of Applied Sciences   
2          Università Cattolica del Sacro Cuore   
3                        University of Bradford   
4                       University of Liverpool   
..                                          ...   
231  University of the West of England, Bristol   
232               University of Gloucestershire   
233           Kuehne Logistics University - KLU   
234                    York University (Canada)   
235                    University of Portsmouth   

                                           description  \
0    The Master’s in Finance prepares students for ...   
1    How do you keep a large organisation healthy? ...   
2    The Banking and Finance programme is a special...   
3    A Master's degree designed to produce fully ro...   
4    A career in finance and investment management ...   
..                                                 ...   
231  Today's business managers need to be able to a...   
232  The modules you will study include Leading Eng...   
233  Our MSc in Global Logistics and Supply Chain M...   
234  The “must-have” degree for specialized financi...   
235  Establish yourself in the global construction ...   

                                                   url  similarity  
0    https://www.findamasters.com/masters-degrees/c...    0.217332  
1    https://www.findamasters.com/masters-degrees/c...    0.112300  
2    https://www.findamasters.com/masters-degrees/c...    0.101381  
3    https://www.findamasters.com/masters-degrees/c...    0.082781  
4    https://www.findamasters.com/masters-degrees/c...    0.082547  
..                                                 ...         ...  
231  https://www.findamasters.com/masters-degrees/c...    0.000000  
232  https://www.findamasters.com/masters-degrees/c...    0.000000  
233  https://www.findamasters.com/masters-degrees/c...    0.000000  
234  https://www.findamasters.com/masters-degrees/c...    0.000000  
235  https://www.findamasters.com/masters-degrees/c...    0.000000  

[236 rows x 5 columns]

The search results seem to be pretty good!

## 3.Define a new score!

### 3.1 Using the input, exploiting the search engine

In [268]:
# In order to exploit the search engine we gave the user the option to write the query as an input
results = execute_query2(str(input("Write here your description query: ")), terms2, dataset, tfidf_data)
(results)

courseName  \
0      Master of Science and Technology in Data and...   
1      Geo-information Science and Earth Observatio...   
2      Computer Science with Data Analytics (100% o...   
3                     Applied Analytical Chemistry MSc   
4                                     Data Science MSc   
..                                                 ...   
331       MSc Data Science and Artificial Intelligence   
332                            DDM Marketing & Finance   
333               DDM Strategic Marketing Intelligence   
334                             Design Informatics MSc   
335               Diagnostics, Data and Digital Health   

                universityName  \
0          Ecole Polytechnique   
1         University of Twente   
2             Keele University   
3    University College London   
4    University of East London   
..                         ...   
331    University of Liverpool   
332    University of Groningen   
333    University of Groningen   
334    University of Edinburgh   
335      University of Warwick   

                                           description  \
0    The MSc&T “Data and Economics for Public Polic...   
1    INTERESTED IN A CAREER IN SPATIAL DATA SCIENCE...   
2    A cutting-edge online MSc Computer Science wit...   
3    Analytical chemistry underpins many important ...   
4    The MSc in Data Science is aimed at providing ...   
..                                                 ...   
331  Pursue a career in this high-demand sector whi...   
332  Would you like to expand and deepen your knowl...   
333  Would you like to learn how to deliver value t...   
334  Design informatics combines data science with ...   
335  Explore the design, development and applicatio...   

                                                   url  similarity  
0    https://www.findamasters.com/masters-degrees/c...    0.126215  
1    https://www.findamasters.com/masters-degrees/c...    0.105122  
2    https://www.findamasters.com/masters-degrees/c...    0.093067  
3    https://www.findamasters.com/masters-degrees/c...    0.048487  
4    https://www.findamasters.com/masters-degrees/c...    0.047901  
..                                                 ...         ...  
331  https://www.findamasters.com/masters-degrees/c...    0.000000  
332  https://www.findamasters.com/masters-degrees/c...    0.000000  
333  https://www.findamasters.com/masters-degrees/c...    0.000000  
334  https://www.findamasters.com/masters-degrees/c...    0.000000  
335  https://www.findamasters.com/masters-degrees/c...    0.000000  

[336 rows x 5 columns]

### 3.2 Score function

Before diving into the exercise, let's get a brief understanding of what the HEAP DATA STRUCTURE is. ([link](https://www.geeksforgeeks.org/heap-data-structure/))

A heap is a specialized tree-based data structure that satisfies the heap property. Heaps are commonly used to implement priority queues, where elements with higher priorities are served before elements with lower priorities. The heap property allows for efficient retrieval and removal of the element with the highest (or lowest) priority.

**Operations of Heap Data Structure:**

- **Heapify**: a process of creating a heap from an array.
- **Insertion**: process to insert an element in existing heap time complexity O(log N).
- **Deletion**: deleting the top element of the heap or the highest priority element, and then organizing the heap and returning the element with time complexity O(log N).
- **Peek**: to check or find the first (or can say the top) element of the heap.

**Types of Heap Data Structure**

Generally, Heaps can be of two types:

- **Max-Heap**: In a Max-Heap the key present at the root node must be greatest among the keys present at all of it’s children. The same property must be recursively true for all sub-trees in that Binary Tree.
- **Min-Heap**: In a Min-Heap the key present at the root node must be minimum among the keys present at all of it’s children. The same property must be recursively true for all sub-trees in that Binary Tree.

Firstly, we enhanced the *execute_query2* function by incorporating a condition to handle an empty query (""): the similarity is set to 1 with all documents and all documents are returned. Additionally, we expanded the number of referenced columns to facilitate the implementation of the *score_function*.

In [269]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def execute_query3(query, inverted_index, dataset, tfidf_dat):
    if not query:  # Check if the query is empty
        # If the query is empty, set similarity to 1 for all documents
        similarity_scores = np.ones(dataset.shape[0])
        results = dataset.copy()
    else:
        # Preprocess the query to match the document processing
        query_terms = [porterstemmer.stem(word) for word in query.lower().split()]

        # Find documents that contain all terms in the query
        relevant_docs = set()
        for term in query_terms:
            if term in inverted_index['term'].values:
                docs_with_term = [doc_id for doc_id, _ in inverted_index.loc[inverted_index['term'] == term, 'tfidf_tuples'].iloc[0]]
                if not relevant_docs:
                    relevant_docs = set(docs_with_term)
                else:
                    relevant_docs.intersection_update(docs_with_term)

        if not relevant_docs:
            return pd.DataFrame()  # If no documents are found, return an empty DataFrame

        # Calculate cosine similarity for each document
        query_vec = tfidf.transform([' '.join(query_terms)])
        similarity_scores = []
        for doc_id in relevant_docs:
            doc_vec = tfidf_data.loc[doc_id].values.reshape(1, -1)
            similarity_scores.append(cosine_similarity(query_vec, doc_vec)[0][0])

        results = dataset.loc[list(relevant_docs), ['courseName', 'universityName', 'description', 'url', 'city', 'country', 'fees_in_usd', 'modality', 'administration', 'startDate', 'isItFullTime']]
        results['similarity'] = similarity_scores

    return results.reset_index(drop=True)



Secondly, we created the function find_top_k_doc which serves the purpose of identifying the top-k documents based on a specified scoring mechanism.

In [270]:
import heapq

def find_top_k_doc(k, dataset_dummy):
    top_documents_heap = []
    # Add the documents to the heap
    for index, row in dataset_dummy.iterrows():
        document_score = row['final_score']
        document_info = (-document_score, index)  # Use negation for max heap
        if len(top_documents_heap) < k:
            heapq.heappush(top_documents_heap, document_info)
        else:
            # If the heap is already of size k,compare the score of the current document with the maximum score in the heap
            max_score, max_index = -top_documents_heap[0][0], top_documents_heap[0][1]
            # If the current document has a higher score than the maximum score in the heap, replace the maximum with the current document
            if document_score > max_score:
                heapq.heappop(top_documents_heap)
                heapq.heappush(top_documents_heap, document_info)

    # Indices of the top-k documents from the heap
    top_documents_indices = [index for _, index in top_documents_heap]
    # Top-k documents from dataset_dummy
    top_documents = dataset_dummy.loc[top_documents_indices]
    return top_documents


In order to get the max heap using find_top_k_doc we used a negation of the document score when inserting into the heap and extracting the max score from the heap. This allows us to simulate a max heap behavior in Python, as the heapq library provides a min heap by default.


In order to create a scoring function we focused on the following columns:
- *modality*
- *administration*
- *startDate*

We decided to weight differently some values according to different logics explained in the code comments

We did not use the column *fees_in_usd* as there are too many null values

In [271]:
def score_function():
    dataset_dummy = execute_query3((input("Write here your description query: ")), terms2, dataset, tfidf_data)

    # Add the weighted_modality column
    modality_binary = dataset['modality'].str.get_dummies(', ') #Dataset of binary values for each value of the modality
    total_columns_modality = modality_binary.sum(axis=1) # Total per row of the ones
    weighted_total_modality = (
        0.10 * modality_binary['MSc'] +    # Weight 'MSc' more as it is the main purpose of this research
        0.025 * modality_binary['Other'] +  # Weight 'Other' less as there are already many options different to MSc so this value is not very important
        (1 - 0.10 - 0.025) * total_columns_modality  # Weight of other columns
    )
    dataset_dummy['weighted_modality'] = weighted_total_modality / total_columns_modality # Add the column to the dataset

    # Add the weighted_administration column
    administration_binary = dataset['administration'].str.get_dummies(', ')
    total_columns_administration = administration_binary.sum(axis=1)
    dataset_dummy['weighted_administration'] = total_columns_administration / administration_binary.shape[1]

    # Add the weighted_startDate column
    startDate_binary = dataset['startDate'].str.get_dummies(', ')
    startDate_binary['total_columns_startDate'] = startDate_binary.sum(axis=1)
    startDate_binary['weighted_total_startDate'] = (
        0 * startDate_binary['See Course'] +  # Weight 'See Course' as 0 as it doesn't provide any information
        startDate_binary['total_columns_startDate']  # Weight other columns
      )
    startDate_binary.weighted_startDate = startDate_binary['weighted_total_startDate']  / startDate_binary['total_columns_startDate']
    # Consider 'weighted_startDate' = 1 where in  dataset.startDate there is 'Any Month'
    startDate_binary.loc[startDate_binary['Any Month'] == 1, 'weighted_startDate'] = 1
    dataset_dummy['weighted_startDate'] = startDate_binary.weighted_startDate

    selected_columns = ['courseName', 'universityName', 'description', 'url', 'city', 'country', 'fees_in_usd', 'weighted_modality', 'weighted_administration', 'weighted_startDate', 'isItFullTime', 'similarity']
    existing_columns = set(selected_columns).intersection(dataset_dummy.columns)
    dataset_dummy = dataset_dummy[list(existing_columns)]
    # If the user gives as an input an empty query then the similarity doesn't need to be calculated as part of the mean to calculate the final score
    if 'similarity' in existing_columns:
        dataset_dummy['final_score'] = dataset_dummy[['weighted_modality', 'weighted_administration', 'weighted_startDate', 'similarity']].mean(axis=1)
    else:
        dataset_dummy['final_score'] = dataset_dummy[['weighted_modality', 'weighted_administration', 'weighted_startDate']].mean(axis=1)

    # Find the top-k documents
    print(f'There are {len(dataset_dummy)} documents')
    k = int(input("How many documents would you like to see?"))
    if k <= len(dataset_dummy):
        return find_top_k_doc(k, dataset_dummy)
    else:
        print("You asked for too many documents, here are all of them")
    return find_top_k_doc(len(dataset_dummy), dataset_dummy)

scored_master = score_function()
print(scored_master)

C:\Users\HP\AppData\Local\Temp\ipykernel_7184\1965424007.py:26: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  startDate_binary.weighted_startDate = startDate_binary['weighted_total_startDate']  / startDate_binary['total_columns_startDate']


There are 336 documents
                                          description  isItFullTime  \
77  The master's programme Management & Data Scien...          True   
4   *SCHOLARSHIPS AVAILABLE* This new MSc programm...          True   
2   As global discussions are increasingly focused...          True   
1   With a clear focus on forensics and industry p...          True   
0   With a clear focus on forensics and industry p...          True   
5   Artificial Intelligence technologies are being...          True   
6   The aim of this programme is to provide indivi...          True   
7   The programme focuses on science (including th...          True   
8   Our MSc Environmental Science for Sustainabili...          True   
9   Within conservation science, there is increasi...         False   

    weighted_startDate                                         courseName  \
77                 1.0                  Management & Data Science (M.Sc.)   
4                  1.0    Applied Artifi

## 4.Visualizing the most relevant MSc degrees

We import all the libraries we are going to need for this exercise

In [125]:
# Load the required libraries
import pandas as pd
from keplergl import KeplerGl
from ydata_profiling import ProfileReport
from googlemaps import Client as GoogleMaps
import googlemaps
import gmaps
import geopandas as gpd
import itertools


For this exercise we are going to chose all the columns of the document imported without the weights

In [128]:
ex4_coor = scored_master[['courseName','universityName','city','country','fees_in_usd','final_score']]


We Will create a new column named Full Address that we are going to search the location

In [130]:
# Create a new column called Full Address
ex4_coor['Full_Address'] = ex4_coor['city'].astype(str) + ',' + ex4_coor['country']

C:\Users\HP\AppData\Local\Temp\ipykernel_7184\665694315.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ex4_coor['Full_Address'] = ex4_coor['city'].astype(str) + ',' + ex4_coor['country']


We import the API key from the google console to use the map extension

In [131]:
from geopy.geocoders import GoogleV3
geolocator = GoogleV3(api_key='AIzaSyBXjLQMkm7N7Be4TylL65QS6WfS0oNxFdQ')


We use first the university name, and if the location is not found then we use the full address

In [133]:
# we create our lists
universities = ex4_coor['universityName']
cities = ex4_coor['Full_Address']

# empty list where store our data
latitudes=[]
longitudes=[]

# we first look in universities name
for i in range(len(universities)):
   location = geolocator.geocode(universities.iloc[i])
   if location is None:
       # we then search in full address in case the university wasn't found
       location = geolocator.geocode(cities.iloc[i])
       if location is None:
           latitudes.append(None)
           longitudes.append(None)
       else:
           # we add the coordinates
           latitudes.append(location.latitude)
           longitudes.append(location.longitude)
       time.sleep(1)
   else:
       # we add the coordinates
       latitudes.append(location.latitude)
       longitudes.append(location.longitude)
   time.sleep(1)

# we add the coordinates to our dataframe
ex4_coor['latitude'] =latitudes
ex4_coor['longitude'] =longitudes


C:\Users\HP\AppData\Local\Temp\ipykernel_7184\1111370830.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ex4_coor['latitude'] =latitudes
C:\Users\HP\AppData\Local\Temp\ipykernel_7184\1111370830.py:31: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ex4_coor['longitude'] =longitudes


In [134]:
# we create a new dataframe that has the columns needed for the map
mapping = ex4_coor[['courseName','universityName','Full_Address','final_score','fees_in_usd','latitude','longitude']]

Here was a little misunderstanding of the exercise and we made a functino to calculate the distance between universities.
It gets a bit messy when there is more than 5 universities to represent in the map. That's why we are going to pass throught it.
But feel free to try it if you want

In [135]:
# import math

# def distance(lat1, lon1, lat2, lon2):
#     # we convert latitude and longitude from degrees to radians
#     lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])

#     # we calculate the differences in coordinates
#     dlat = lat2 - lat1
#     dlon = lon2 - lon1

#     # we use the haversine formula to calculate the distance between pints in a sphere
#     a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
#     c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
#     radius_of_earth = 6371  # we write the radius of the Earth in kilometers

#     # We calculate the distance in km
# #     distance = radius_of_earth * c
#     distance = "{:.2f} km".format(radius_of_earth * c)
#     return distance



In [136]:
# # This is a function to calculate the distance in case we want to show them in the map
# dfarc = mapping[['courseName','latitude','longitude']]

# # we create all possible pairs of Masters
# pairs = list(itertools.combinations(dfarc.index, 2))

# # we create a new df for the arcs
# arcs = pd.DataFrame()

# # we create a row in the df
# for pair in pairs:
#     arc = pd.DataFrame({
#         'start_latitude': [dfarc.loc[pair[0], 'latitude']],
#         'start_longitude': [dfarc.loc[pair[0], 'longitude']],
#         'end_latitude': [dfarc.loc[pair[1], 'latitude']],
#         'end_longitude': [dfarc.loc[pair[1], 'longitude']],
#         'Distance': distance(dfarc.loc[pair[0], 'latitude'], dfarc.loc[pair[0], 'longitude'],
#                           dfarc.loc[pair[1], 'latitude'], dfarc.loc[pair[1], 'longitude'])
#     })
#     arcs = pd.concat([arcs, arc], ignore_index=True)


This next code is the configuration of the map. We had it because the KeplerGl mapping allows you to make all the modifications needed in the map directly from the map itself. then with the code 'map.config' you get this output, that was the one use for our mapping.

To define this configurations allow us to always have the same type of map each time we run a new data.

In [137]:
configuration = {'version': 'v1',
 'config': {'visState': {'filters': [],
   'layers': [{'id': 'ctgnkz',
     'type': 'point',
     'config': {'dataId': 'kepler map',
      'label': 'Fee',
      'color': [136, 87, 44],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat': 'latitude',
       'lng': 'longitude',
       'altitude': 'fees_in_usd'},
      'isVisible': True,
      'visConfig': {'radius': 10,
       'fixedRadius': False,
       'opacity': 0.8,
       'outline': False,
       'thickness': 2,
       'strokeColor': None,
       'colorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'strokeColorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'radiusRange': [0, 50],
       'filled': True},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'fees_in_usd',
       'type': 'integer'},
      'colorScale': 'quantize',
      'strokeColorField': None,
      'strokeColorScale': 'quantile',
      'sizeField': None,
      'sizeScale': 'linear'}},
    {'id': 'k5ptiqg',
     'type': 'geojson',
     'config': {'dataId': 'kepler map',
      'label': 'Master',
      'color': [255, 153, 31],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'geojson': 'geometry'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'strokeOpacity': 0.8,
       'thickness': 0.5,
       'strokeColor': None,
       'colorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'strokeColorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'radius': 10,
       'sizeRange': [0, 10],
       'radiusRange': [0, 50],
       'heightRange': [0, 500],
       'elevationScale': 5,
       'enableElevationZoomFactor': True,
       'stroked': False,
       'filled': True,
       'enable3d': False,
       'wireframe': False},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': None,
      'colorScale': 'quantile',
      'strokeColorField': None,
      'strokeColorScale': 'quantile',
      'sizeField': None,
      'sizeScale': 'linear',
      'heightField': None,
      'heightScale': 'linear',
      'radiusField': None,
      'radiusScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'kepler map': [{'name': 'courseName',
        'format': None},
       {'name': 'Full_Address', 'format': None},
       {'name': 'universityName', 'format': None},
       {'name': 'fees_in_usd', 'format': None},
       {'name': 'final_score', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 53.018719484005445,
   'longitude': 12.899637073453919,
   'pitch': 0,
   'zoom': 2.5140140567993456,
   'isSplit': False},
  'mapStyle': {'styleType': 'dark',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'border': False,
    'building': True,
    'water': True,
    'land': True,
    '3d building': False},
   'threeDBuildingColor': [9.665468314072013,
    17.18305478057247,
    31.1442867897876],
   'mapStyles': {}}}}

Now we are going to create the map with all the different coordinates and information that we have.

In [138]:
# we create a basemap
map1 = KeplerGl(height=600, width=800)#show the map# Create a gepdataframe
# with the coordinates
gdf1 = gpd.GeoDataFrame(mapping, geometry=gpd.points_from_xy(mapping.longitude, mapping.latitude))

gdf1['fees_in_usd'] = mapping['fees_in_usd']# Add data to Kepler

map1.add_data(data=gdf1, name='kepler map') # adding geo enabled dataframe to map

# map1.add_data(data=arcs, name='arcs') # we add the arcs that show the distance between masters (only if wanted)

# we add our configuration from above
map1.config=configuration
map1

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter


KeplerGl(config={'version': 'v1', 'config': {'visState': {'filters': [], 'layers': [{'id': 'ctgnkz', 'type': '…

We are going to create an html file so we can see it outside the notebook

In [272]:
map1.save_to_html(file_name='keplergl_map.html')


Map saved to keplergl_map.html!


As we can see in this map, each point represent a Master degree. In those master degree we have all the information needed for the student. The university name, the location, the fee and the score.

Moreover he can have a direct look at the fee thanks to the different colors of the dots. Since in the legend we can see the different colors for each range of fee. (Click in the little list at the right of the map)


## 5.BONUS: More complex search engine

For this question we are going to do very similar things than for the ex 2, but joining the columns 'courseName', 'city' and 'universityName' to make a new terms and index.

In [139]:
datasearch = dataset
# we join the columns needed
datasearch['search_column'] =  datasearch['courseName'] + ', ' + datasearch['city'] + ', ' + datasearch['universityName']
datasearch['search_column'] = datasearch.search_column.apply(lambda row: [porterstemmer.stem(word) for word in nltk.word_tokenize(row) if not word in lst_stopwords and word.isalnum()])

#create a vocabulary
vocabulary_search = Counter(reduce(lambda x, y: x + y, datasearch.search_column.values)).keys()

# create the index
index_search = {}
unique_id = 1
for word in list(vocabulary_search):
  index_search[unique_id] = word
  unique_id+=1

  # we create our new terms
terms_search = pd.DataFrame(data=list(vocabulary_search), columns=['term'])
# and the reverse column
terms_search['reverse'] = terms_search.term.progress_apply(lambda item: list(datasearch.loc[datasearch.search_column.apply(lambda row: item in row)].index))

  0%|          | 0/1716 [00:00<?, ?it/s]

If wanted we can put it in a csv file

In [140]:
terms_search.to_csv('inverted_search_index.csv', index=False)

Now we continue to do the tfidf to be able to calculate the similarity

In [141]:
results_search = tfidf.fit_transform(datasearch.search_column)
result_dense_search = results_search.todense()
tfidf_data_search = pd.DataFrame(result_dense_search.tolist(), index=datasearch.index, columns=tfidf.get_feature_names_out())

cossim_data_search = pd.DataFrame(cosine_similarity(tfidf_data_search), index=datasearch.index, columns=datasearch.index)

terms2_search = terms_search[['term', 'reverse']].copy()
terms2_search['tfidf_tuples'] = terms2_search.term.apply(lambda term: [(doc_id, tfidf_data_search.loc[doc_id, term])
                                                       for doc_id in tfidf_data_search.index if tfidf_data_search.loc[doc_id, term] > 0])

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


We make our functions

In [142]:
def execute_query_5(query, inverted_index, dataset, tfidf_data): # this one is going to ne used to search the course name with the similarity
    # Preprocess the query to match the document processing
    query_terms = [porterstemmer.stem(word) for word in query.lower().split()]

    # Find documents that contain all terms in the query
    relevant_docs = set()
    for term in query_terms:
        if term in inverted_index['term'].values:
            docs_with_term = [doc_id for doc_id, _ in inverted_index.loc[inverted_index['term'] == term, 'tfidf_tuples'].iloc[0]]
            if not relevant_docs:
                relevant_docs = set(docs_with_term)
            else:
                relevant_docs.intersection_update(docs_with_term)

    if not relevant_docs:
        return pd.DataFrame()  # If no documents are found, return an empty DataFrame

    # Calculate cosine similarity for each document
    query_vec = tfidf.transform([' '.join(query_terms)])
    similarities = {}
    for doc_id in relevant_docs:
        doc_vec = tfidf_data.loc[doc_id].values.reshape(1, -1)
        similarities[doc_id] = cosine_similarity(query_vec, doc_vec)[0][0]

    # Sort documents by their similarity score
    sorted_doc_ids = sorted(similarities, key=similarities.get, reverse=True)

    # Prepare the results with the similarity score
    results = dataset.loc[sorted_doc_ids]
    results['similarity'] = [similarities[doc_id] for doc_id in sorted_doc_ids]

    return results #here we should only return the courses with similarity > 0

def execute_query_6(query, inverted_index, dataset): #this one to search all the cities and universities we are looking for
    # Split the query into terms and stem each term
    query_terms = [porterstemmer.stem(word) for word in query.lower().split()]

    # Retrieve the list of document indices for each query term
    list_of_documents = [set(inverted_index[inverted_index['term'] == term_i]['reverse'].values[0])
                         for term_i in query_terms if term_i in inverted_index['term'].values]

    # Union the document lists to find documents that contain at least one query term
    if list_of_documents:
        docs_containing_one_term = set.union(*list_of_documents)
        # Filter out indices not present in the dataset
        docs_containing_one_term = [doc_id for doc_id in docs_containing_one_term if doc_id in dataset.index]
    else:
        docs_containing_one_term = []

    results = dataset.loc[docs_containing_one_term]

    return results.reset_index(drop=True)


And once we have all the functions we can make our search engine!!

You just have to answer the progressive questions.

In [143]:
search_results = datasearch

if input('Are you looking for a specific course? (yes/no)') == 'yes':
    search_query = input('What course are you looking for?')
    search_results = execute_query_5(search_query, terms2_search, search_results, tfidf_data_search)


if input('Are you looking for a specific city or university? (yes/no)') == 'yes':
    search_query = input('What cities or universities are you looking for?')
    search_results = execute_query_6(search_query, terms_search, search_results)


if input('Are you looking for a range of fees? (yes/no)') == 'yes':
    fee_min = int(input('Minimun fee (USD)'))
    fee_max = int(input('Minimun fee (USD)'))
    search_results = search_results[(search_results['fees_in_usd'] >= fee_min) & (search_results['fees_in_usd'] <= fee_max)]

if input('Are you looking for a specific country? (yes/no)') == 'yes':
    countries_search=(input('In what countries are you looking the masters? (only country names)').split())
    search_results = search_results[search_results['country'].str.lower().isin(countries_search)]


started = input('Are you looking for a master that has already started? (yes/no)')

modality_online = input('Are you looking for a master that has online modality? (yes/no)')

if started == 'yes':
    start_search = ('september','october','november','any month')
    search_results = search_results[search_results['startDate'].str.lower().isin(start_search)]

if modality_online == 'yes':
    modality_search = ['online']
    search_results = search_results[search_results['administration'].str.lower().isin(modality_search)]

final_results = search_results[['courseName','universityName','url']]
(final_results)




courseName                                   universityName  \
5    M.Sc. Data Science  IU International University of Applied Sciences   

                                                 url  
5  https://www.findamasters.com/masters-degrees/c...


## 6.Command Line Question (CLQ)

#### This is the Command line code:

awk  '(NR == 1) || (FNR > 1)' *.tsv > merged_courses.tsv

awk -F'\t' '{print $10, $11}' merged_courses.tsv | sort | uniq -c | sort -nr | head -n 1

awk -F'\t' '$9~/part/ || $9~/Part/' merged_courses.tsv | awk -F'\t' '{print $1}' | sort | uniq -c | wc -l

total_courses=$(($(wc -l < merged_courses.tsv) - 1))

engineering_courses=$(awk -F '\t' '$1 ~ /Engineer/ {print $0}' merged_courses.tsv | wc -l)

percentage=$(echo "scale=2; ($engineering_courses / $total_courses) * 100" | bc)

percentage=$(printf "%.0f" $percentage)

echo "Percentage of Engineering courses: $percentage%"

#### And here is the result

In [144]:
  from IPython.display import Image
  Image(url="ADM-HW3-CL.png")


## 7.Algorithmic Question

### 1.Implement a code to solve the above mentioned problem


In [145]:
# Produced the report
def find_report(array, target, row_index, current_sum, elements):
    if row_index == len(array):
        if current_sum == target:
            return elements
        else:
            return []

    for i in range(len(array[row_index])):
        if current_sum + array[row_index][i] > target:
            break
        result = find_report(array, target, row_index + 1, current_sum + array[row_index][i], elements + [array[row_index][i]])
        if len(result) == len(array):
            return result
    return []


# Checking if report can be generated
def isReportPossible(days, sumHours, limits):
    """
    Function to check if report can be generated and produce it.

    Args:
        dats: the number of days employee worked.
        sumHours: total number of hours employee worked.
        limits: array of tuples contains two integer indicating min and max hours employee can work.

    Print:
        No - if report can not be generated
        Yes- if report can be generated + the possible report
    """
    sum_max = 0
    sum_min = 0
    for j in limits:
        sum_max += j[1]
        sum_min += j[0]
    if sumHours > sum_max or sumHours < sum_min:
        print('No')
    else:
        print('Yes')
        x = []
        if sumHours == sum_max:
            for i in limits:
                x.append(i[1])
            print(x)
        elif sumHours == sum_min:
            for i in limits:
                x.append(i[0])
            print(x)
        else:
            for i in limits:
                interval = list(range(i[0],i[1]+1))
                x.append(interval)
            print(find_report(x, sumHours, 0, 0, []))

In [146]:
# Reciving the input from the user
limits =[]
days, sumHours =  map(int, input().split())
for i in range(days):
    x, y =  map(int, input().split())
    limit = (x,y)
    limits.append(limit)
isReportPossible(days, sumHours, limits)

Yes
[0, 5]


### 2.What is the time complexity?

In the first step of our algorithm we call the 'isReportPossible' function, which has a runnin time O(n)- where n is the lenth of limitation (the input).   
This is because we go over all limits the user gave us and sum their start and end points.  
If 'isReportPossible' print 'No'- we are done.  
If 'isReportPossible' print 'Yes'- we call the 'find_report' function.    

Before calling the 'find_report' function, we check if the target sum is the maximal or minimal- which is easy to find and takes O(n).  
If not we define our "new" array where row_i contain all the values in the interval limit_i.  
For example if limit_i = (2,4) then row_i = [2,3,4].  
Note that the maximal length of an interval is 24, since there are only 24 hours a day.  
So 24 is an upper bound for our intervals length.  
Therefore denote K- as the maximal interval length of our input.  
We get this step is done by O(n * K) <= O(n * 24) = O(n).

Note that our 'find_report' function is going over **all possible** reports and return the desired one.  
This is done by going over all element of the array O(n * K) and call the function recursivly,  
resulting in exponential time complexity - O(K^n)   

Note that once the function finds a solution- it returns it.   
Therefore in the average case,the function wont traverses through the entire array.

Overall we get: O(n) + O(K^n) = O(K^n)

### 3.LLM Running Time Analysis
The time complexity of the isReportPossible function is O(n) because the most time-consuming operation is iterating over the limits list.   
However, the actual running time of the function can be affected by various factors such as the hardware you're running the code on, the load on the system, and other processes running on the system.

The find_report function in your code is a recursive function that traverses through an array. It checks if the current sum is less than or equal to the target and if so, it calls itself with the next index and the updated current sum. The time complexity of such a function is typically O(n), where n is the number of elements in the array. This is because in the worst-case scenario, the function may need to traverse through all the elements in the array. However, the actual time complexity can be higher if the function keeps calling itself without finding a solution.


**It is clear that the machine's answer is incorrect because it claims that the running time is linear while it is clear that the running time is exponential.**

### 4.Optimal Solution

After seeing that the running time in the first algorithm we proposed is exponential,  
we thought of another algorithm with a linear running time.
Below is the code:

In [147]:
def find_report_min(limits, array, diff, elements):
    for i, limit in enumerate(limits):
        if diff != 0:
            if array[i] >= diff:
                elements.append(limit[0] + diff)
                diff = 0
            else:
                elements.append(limit[0])
        else:
            elements.append(limit[0])
    print(elements)

def find_report_max(limits, array, diff, elements):
    for i, limit in enumerate(limits):
        if diff != 0:
            if array[i] >= diff:
                elements.append(limit[1] - diff)
                diff = 0
            else:
                elements.append(limit[1])
        else:
            elements.append(limit[1])
    print(elements)


def isReportPossible_new(days, sumHours, limits):
    """
    Function to check if report can be generated and produce it.

    Args:
        dats: the number of days employee worked.
        sumHours: total number of hours employee worked.
        limits: array of tuples contains two integer indicating min and max hours employee can work.

    Print:
        No - if report can not be generated
        Yes- if report can be generated + the possible report
    """
    sum_max = 0
    sum_min = 0
    for j in limits:
        sum_max += j[1]
        sum_min += j[0]
    if sumHours > sum_max or sumHours < sum_min:
        print('No')
    else:
        print('Yes')
        x = []
        if sumHours == sum_max:
            for i in limits:
                x.append(i[1])
            print(x)
        elif sumHours == sum_min:
            for i in limits:
                x.append(i[0])
            print(x)
        else:
            for i in limits:
                x.append(i[1] - i[0])
            if sumHours - sum_min < sum_max - sumHours:
                diff = sumHours - sum_min
                find_report_min(limits, x, diff, [])
            else:
                diff = sum_max - sumHours
                find_report_max(limits, x, diff, [])


In [148]:
# Reciving the input from the user
limits =[]
days, sumHours = map(int, input().split())
for i in range(days):
    x, y = map(int, input().split())
    limit = (x,y)
    limits.append(limit)
isReportPossible_new(days, sumHours, limits)

Yes
[0, 5]


- In this algorithm, we go through each element in limits array only once,  
and therefore the running time is O(n)